export type DataConnectionConceptName =
  | 'Tier 1-4'
  | 'Data Authority & Evidence'
  | 'Hybrid'
  | 'Individual';

export type AnalysisContractStatus =
  | 'CANONICAL'
  | 'COMPATIBILITY_ONLY'
  | 'RESEARCH_ONLY'
  | 'CONTEXT_ONLY'
  | 'BLOCKED'
  | 'DISABLED';

export type AnalysisAssetClass =
  | 'crypto'
  | 'stock'
  | 'forex'
  | 'index'
  | 'commodity'
  | 'bond'
  | 'portfolio'
  | 'multi-asset';

export interface AnalysisBenchmarkProfile {
  readonly runtimeCostClass: 'LOW' | 'MEDIUM' | 'HIGH';
  readonly evidenceStrength: 1 | 2 | 3 | 4 | 5;
  readonly integrationComplexity: 1 | 2 | 3 | 4 | 5;
  readonly providerLatencyMeasured: false;
}

export interface AnalysisConnectionContract {
  readonly id: string;
  readonly conceptName: DataConnectionConceptName;
  readonly toolName: string;
  readonly kind: 'SCORING' | 'ANALYSIS' | 'RANKING' | 'PORTFOLIO';
  readonly assetClasses: readonly AnalysisAssetClass[];
  readonly subclasses: readonly string[];
  readonly bestConcept: string;
  readonly status: AnalysisContractStatus;
  readonly bindingSequence: readonly string[];
  readonly providerApplicationServices: readonly string[];
  readonly storageModels: readonly string[];
  readonly uiFlow: readonly string[];
  readonly scoringModel: string;
  readonly formula: string;
  readonly sourceRefs: readonly string[];
  readonly benchmark: AnalysisBenchmarkProfile;
}

export interface DataConnectionConceptDefinition {
  readonly name: DataConnectionConceptName;
  readonly summary: string;
  readonly layers: readonly string[];
}

export const DATA_CONNECTION_CONCEPTS: readonly DataConnectionConceptDefinition[] = Object.freeze([
  {
    name: 'Tier 1-4',
    summary: 'Live-Market-Data-Pipeline von Multi-Provider Ingestion bis Client/Scorer, optimiert für niedrige Latenz und Fan-out.',
    layers: [
      'Tier 1 · ProviderRegistry → ProviderMatrix → MarketDataGateway',
      'Tier 2 · CircuitBreaker / RateLimitBudget / RequestCoalescer → MarketTickGate / DataQualityService',
      'Tier 3 · MarketDataCache / RingBuffer / PubSub / WebSocket Fan-out',
      'Tier 4 · LiveClientFeed → Scoring/Analysis Consumer → UI',
    ],
  },
  {
    name: 'Data Authority & Evidence',
    summary: 'Evidence-first Pfad mit Provenance, Freshness, Data Quality, Feature- und Scoring-Lineage vor jeder UI-Projektion.',
    layers: [
      'Provider / Evidence Adapter',
      'Evidence Identity + Provenance + Freshness',
      'ValidatedDataInput → ValidatedFeatureInput',
      'ScoringModelRegistry → ScoringDispatcher → CanonicalScoreResult',
      'Read-only UI / Ranking / Decision Support',
    ],
  },
  {
    name: 'Hybrid',
    summary: 'Kombiniert den Live-Tier-1-4-Pfad mit Evidence-/Authority-Gates vor dem produktiven Scoring.',
    layers: [
      'Live Provider Ingestion',
      'Gate & Norm',
      'Cache / Fan-out',
      'Evidence + DQ + Feature Lineage',
      'Canonical Scoring / Analysis',
      'UI',
    ],
  },
  {
    name: 'Individual',
    summary: 'Spezialisierter Adapter- und Feature-Pfad für einzelne Asset-Unterklassen; produktive Scores bleiben trotzdem an kanonische Gates gebunden.',
    layers: [
      'Dedicated Provider Adapter',
      'Specialized Evidence Contract',
      'Specialized Feature Engineering',
      'Domain Engine / Research Evaluator',
      'Canonical Adapter when productive',
      'UI',
    ],
  },
]);

const hybridLiveSequence = [
  'ProviderRegistry',
  'ProviderMatrix',
  'MarketDataGateway',
  'CircuitBreaker / RateLimitBudget / RequestCoalescer',
  'MarketTickGate / DataQualityService',
  'MarketDataCache / Fanout',
  'Evidence Identity / Provenance',
  'ValidatedDataInput',
  'ValidatedFeatureInput',
  'ScoringModelRegistry',
  'ScoringDispatcher',
  'CanonicalScoreResult',
  'UI',
] as const;

const evidenceSequence = [
  'Provider / Evidence Adapter',
  'Evidence Identity / Provenance / Freshness',
  'Data Quality Gate',
  'ValidatedDataInput',
  'ValidatedFeatureInput',
  'Domain Evaluation',
  'Canonical Adapter or Research Projection',
  'UI',
] as const;

export const ANALYSIS_CONNECTION_CONTRACTS: readonly AnalysisConnectionContract[] = Object.freeze([
  {
    id: 'crypto-technical-provenance',
    conceptName: 'Hybrid',
    toolName: 'Verified Crypto Technical Scorer',
    kind: 'SCORING',
    assetClasses: ['crypto'],
    subclasses: ['BTC', 'ETH', 'Altcoins with verified market-history and snapshot evidence'],
    bestConcept: 'Hybrid: Tier 1-4 live market path + Data Authority/Evidence gate before canonical scoring.',
    status: 'CANONICAL',
    bindingSequence: hybridLiveSequence,
    providerApplicationServices: ['ProviderRegistry', 'ProviderMatrix', 'MarketDataGateway', 'MarketDataHistoryGateway', 'ScoringDispatcher'],
    storageModels: ['MarketDataCache', 'MarketDataRingBuffer', 'CanonicalScoreResult lineage', 'score_snapshots when persisted'],
    uiFlow: ['LiveClientFeed / verified history', 'evaluateVerifiedCryptoTechnicalScore', 'ScoringDispatcher', 'CanonicalScoreResult', 'Enterprise Scorer / Ranking UI'],
    scoringModel: 'crypto-technical-provenance/0.7.0',
    formula: 'renormalized weighted score: trend 22.22% + momentum 17.78% + volatility_quality 13.33% + breakout_quality 11.11% + relative_strength 13.33% + liquidity 8.89% + supply_dynamics 8.89% + inverted data_quality_risk 4.44%. Missing factors are excluded and weights are renormalized.',
    sourceRefs: ['src/services/verifiedCryptoTechnicalScoring.ts', 'src/services/cryptoScoringService.ts', 'src/platform/Scoring/ScoringModelRegistry.ts'],
    benchmark: { runtimeCostClass: 'MEDIUM', evidenceStrength: 5, integrationComplexity: 4, providerLatencyMeasured: false },
  },
  {
    id: 'traditional-scoring-stock',
    conceptName: 'Hybrid',
    toolName: 'Traditional Stock Scoring',
    kind: 'SCORING',
    assetClasses: ['stock'],
    subclasses: ['Equities with verified history and optional fundamentals'],
    bestConcept: 'Hybrid: live/history pricing plus Evidence-first fundamentals and canonical dispatcher.',
    status: 'CANONICAL',
    bindingSequence: hybridLiveSequence,
    providerApplicationServices: ['MarketDataGateway', 'MarketDataHistoryGateway', 'Fundamentals provider adapter', 'ScoringDispatcher'],
    storageModels: ['MarketDataCache', 'FinancialFieldProvenance', 'CanonicalScoreResult lineage'],
    uiFlow: ['Verified history + fundamentals', 'TraditionalAssetScoringService', 'ScoringDispatcher', 'Canonical score', 'Stock analysis UI'],
    scoringModel: 'traditional-scoring/2.1.0 · stock profile',
    formula: 'renormalized weighted score: trend 18% + momentum 14% + breakout 10% + volatility_quality 10% + RSI 13% + value 15% + dividend 8% + quality 12%.',
    sourceRefs: ['src/services/traditionalAssetScoring.ts', 'src/platform/Scoring/ScoringExecutorAdapters.ts'],
    benchmark: { runtimeCostClass: 'MEDIUM', evidenceStrength: 4, integrationComplexity: 3, providerLatencyMeasured: false },
  },
  {
    id: 'traditional-scoring-fx-index',
    conceptName: 'Tier 1-4',
    toolName: 'Traditional FX / Index Scoring',
    kind: 'SCORING',
    assetClasses: ['forex', 'index'],
    subclasses: ['FX pairs', 'Market indices'],
    bestConcept: 'Tier 1-4 for price/history delivery, with the existing DQ and dispatcher gates retained.',
    status: 'CANONICAL',
    bindingSequence: hybridLiveSequence,
    providerApplicationServices: ['ProviderRegistry', 'MarketDataGateway', 'MarketDataHistoryGateway', 'ScoringDispatcher'],
    storageModels: ['MarketDataCache', 'Historical price series', 'CanonicalScoreResult lineage'],
    uiFlow: ['Verified price history', 'TraditionalAssetScoringService', 'ScoringDispatcher', 'Canonical score', 'Market analysis UI'],
    scoringModel: 'traditional-scoring/2.1.0 · FX/index profile',
    formula: 'renormalized weighted score: trend 30% + momentum 25% + breakout 15% + volatility_quality 15% + RSI 15%.',
    sourceRefs: ['src/services/traditionalAssetScoring.ts', 'src/platform/Scoring/ScoringModelRegistry.ts'],
    benchmark: { runtimeCostClass: 'LOW', evidenceStrength: 4, integrationComplexity: 3, providerLatencyMeasured: false },
  },
  {
    id: 'commodity-market-evidence',
    conceptName: 'Data Authority & Evidence',
    toolName: 'Commodity Market Evidence Scorer',
    kind: 'SCORING',
    assetClasses: ['commodity'],
    subclasses: ['Commodity benchmarks'],
    bestConcept: 'Data Authority & Evidence; commodity score requires complete verified history evidence before execution.',
    status: 'CANONICAL',
    bindingSequence: evidenceSequence,
    providerApplicationServices: ['TwelveDataCommodityHistoryProvider', 'MarketDataHistoryGateway', 'ScoringDispatcher'],
    storageModels: ['CommodityMarketEvidence', 'Evidence refs', 'CanonicalScoreResult lineage'],
    uiFlow: ['Commodity history evidence', 'scoreCommodityMarketEvidence', 'ScoringDispatcher', 'Canonical score', 'Raw Materials UI'],
    scoringModel: 'commodity-evidence-scoring/1.0.0',
    formula: 'trend 30% + momentum 25% + breakout_quality 20% + volatility_quality 25%; 100% factor coverage and minimum history gate required.',
    sourceRefs: ['src/services/commodityEvidenceScoring.ts', 'src/platform/Scoring/ScoringModelRegistry.ts'],
    benchmark: { runtimeCostClass: 'LOW', evidenceStrength: 5, integrationComplexity: 3, providerLatencyMeasured: false },
  },
  {
    id: 'sovereign-benchmark-yield',
    conceptName: 'Data Authority & Evidence',
    toolName: 'Sovereign Benchmark Yield Scorer',
    kind: 'SCORING',
    assetClasses: ['bond'],
    subclasses: ['Government benchmark yields only'],
    bestConcept: 'Data Authority & Evidence; sovereign yield observations are evidence, not execution prices.',
    status: 'CANONICAL',
    bindingSequence: evidenceSequence,
    providerApplicationServices: ['EODHD bond evidence adapter', 'Macro/FRED evidence context', 'ScoringDispatcher'],
    storageModels: ['BondEvidenceResult', 'Evidence refs', 'CanonicalScoreResult lineage'],
    uiFlow: ['Benchmark-yield history', 'scoreSovereignBenchmarkEvidence', 'ScoringDispatcher', 'Canonical score', 'Bond benchmark UI'],
    scoringModel: 'sovereign-benchmark-yield-scoring/1.0.0',
    formula: 'yield_level_percentile 45% + standardized yield_trend 30% + yield_stability 25%; full evidence coverage required.',
    sourceRefs: ['src/services/sovereignBenchmarkEvidenceScoring.ts', 'src/services/eodhdBondEvidence.ts'],
    benchmark: { runtimeCostClass: 'LOW', evidenceStrength: 5, integrationComplexity: 3, providerLatencyMeasured: false },
  },
  {
    id: 'crypto-meme-integrity',
    conceptName: 'Individual',
    toolName: 'Meme-Coin Integrity Research',
    kind: 'ANALYSIS',
    assetClasses: ['crypto'],
    subclasses: ['Meme coins'],
    bestConcept: 'Individual specialized evidence graph feeding the Data Authority plane; keep research-only until promotion gates are satisfied.',
    status: 'RESEARCH_ONLY',
    bindingSequence: evidenceSequence,
    providerApplicationServices: ['GoPlus security/simulation adapters', 'DexScreener evidence', 'Market history adapters', 'Social evidence adapters'],
    storageModels: ['Research evidence refs', 'Feature attestations', 'Research evaluation output'],
    uiFlow: ['Specialized evidence adapters', 'Crypto meme research contract', 'Research evaluator', 'Research-only projection', 'UI'],
    scoringModel: 'crypto-meme-integrity/0.3.0 challenger',
    formula: 'No productive executable weight set. Feature families include execution liquidity, market structure, holder distribution, contract/rug risk, social authenticity, narrative, venue access and hard gates.',
    sourceRefs: ['src/platform/Scoring/CryptoResearchModelContracts.ts', 'src/services/memeCoinScoringService.ts'],
    benchmark: { runtimeCostClass: 'HIGH', evidenceStrength: 4, integrationComplexity: 5, providerLatencyMeasured: false },
  },
  {
    id: 'crypto-defi-fundamental',
    conceptName: 'Individual',
    toolName: 'DeFi Fundamental Research',
    kind: 'ANALYSIS',
    assetClasses: ['crypto'],
    subclasses: ['DeFi protocols / tokens'],
    bestConcept: 'Individual protocol/on-chain evidence adapters joined through Data Authority & Evidence; research-only until promotion.',
    status: 'RESEARCH_ONLY',
    bindingSequence: evidenceSequence,
    providerApplicationServices: ['DefiLlamaProtocolProvider', 'Contract evidence adapters', 'Oracle/security evidence adapters'],
    storageModels: ['Protocol evidence', 'Contract-security evidence', 'Research feature attestations'],
    uiFlow: ['Protocol/on-chain evidence', 'DeFi feature contract', 'Research evaluator', 'Research projection', 'DeFi UI'],
    scoringModel: 'crypto-defi-fundamental/0.3.0 challenger',
    formula: 'No productive executable weight set. Research factors cover utilization, protocol scale/activity, revenue quality, liquidity, concentration, contract security, oracle, tokenomics, governance and ecosystem evidence.',
    sourceRefs: ['src/platform/Scoring/CryptoResearchModelContracts.ts', 'src/platform/MarketData/providers/DefiLlamaProtocolProvider.ts'],
    benchmark: { runtimeCostClass: 'HIGH', evidenceStrength: 4, integrationComplexity: 5, providerLatencyMeasured: false },
  },
  {
    id: 'commodity-energy-hybrid',
    conceptName: 'Hybrid',
    toolName: 'Commodity Energy Research',
    kind: 'ANALYSIS',
    assetClasses: ['commodity'],
    subclasses: ['Energy benchmarks'],
    bestConcept: 'Hybrid: market history + specialized energy fundamentals/evidence; challenger remains non-executable.',
    status: 'RESEARCH_ONLY',
    bindingSequence: evidenceSequence,
    providerApplicationServices: ['Commodity history adapter', 'Energy/EIA evidence adapter', 'Research evaluator'],
    storageModels: ['Commodity evidence', 'Research feature snapshot'],
    uiFlow: ['Market + energy evidence', 'Category research contract', 'Research evaluation', 'UI'],
    scoringModel: 'commodity-energy-hybrid/0.1.0 challenger',
    formula: 'Research-only category composition; no productive canonical weight execution.',
    sourceRefs: ['src/platform/Scoring/CommodityResearchModelContracts.ts'],
    benchmark: { runtimeCostClass: 'MEDIUM', evidenceStrength: 3, integrationComplexity: 4, providerLatencyMeasured: false },
  },
  {
    id: 'commodity-industrial-metals-hybrid',
    conceptName: 'Hybrid',
    toolName: 'Industrial / Critical Metals Research',
    kind: 'ANALYSIS',
    assetClasses: ['commodity'],
    subclasses: ['Industrial metals', 'Critical metals'],
    bestConcept: 'Hybrid with market evidence plus physical-supply/criticality evidence.',
    status: 'RESEARCH_ONLY',
    bindingSequence: evidenceSequence,
    providerApplicationServices: ['Commodity history adapter', 'USGS/physical supply evidence', 'Research evaluator'],
    storageModels: ['Commodity evidence', 'Supply/criticality evidence snapshot'],
    uiFlow: ['Market + physical evidence', 'Category contract', 'Research evaluation', 'UI'],
    scoringModel: 'commodity-industrial-metals-hybrid/0.1.0 challenger',
    formula: 'Research-only category composition; physical supply and criticality remain separate evidence dimensions.',
    sourceRefs: ['src/platform/Scoring/CommodityResearchModelContracts.ts'],
    benchmark: { runtimeCostClass: 'MEDIUM', evidenceStrength: 3, integrationComplexity: 4, providerLatencyMeasured: false },
  },
  {
    id: 'commodity-precious-metals-hybrid',
    conceptName: 'Hybrid',
    toolName: 'Precious Metals Research',
    kind: 'ANALYSIS',
    assetClasses: ['commodity'],
    subclasses: ['Gold', 'Silver', 'Precious-metal benchmarks'],
    bestConcept: 'Hybrid: canonical market evidence plus macro/risk context, without mixing resource-project metrics into benchmark scoring.',
    status: 'RESEARCH_ONLY',
    bindingSequence: evidenceSequence,
    providerApplicationServices: ['Commodity history adapter', 'Macro evidence adapter', 'Research evaluator'],
    storageModels: ['Commodity evidence', 'Macro context evidence'],
    uiFlow: ['Market + macro evidence', 'Category contract', 'Research evaluation', 'UI'],
    scoringModel: 'commodity-precious-metals-hybrid/0.1.0 challenger',
    formula: 'Research-only category composition; no productive canonical weight execution.',
    sourceRefs: ['src/platform/Scoring/CommodityResearchModelContracts.ts'],
    benchmark: { runtimeCostClass: 'MEDIUM', evidenceStrength: 3, integrationComplexity: 4, providerLatencyMeasured: false },
  },
  {
    id: 'commodity-agriculture-hybrid',
    conceptName: 'Hybrid',
    toolName: 'Agriculture Commodity Research',
    kind: 'ANALYSIS',
    assetClasses: ['commodity'],
    subclasses: ['Agriculture benchmarks'],
    bestConcept: 'Hybrid with market history plus point-in-time USDA/physical evidence.',
    status: 'RESEARCH_ONLY',
    bindingSequence: evidenceSequence,
    providerApplicationServices: ['Commodity history adapter', 'USDA/physical evidence adapter', 'Research evaluator'],
    storageModels: ['Commodity evidence', 'Point-in-time release/revision lineage'],
    uiFlow: ['Market + agriculture evidence', 'Category contract', 'Research evaluation', 'UI'],
    scoringModel: 'commodity-agriculture-hybrid/0.1.0 challenger',
    formula: 'Research-only category composition; point-in-time validation is mandatory before any promotion.',
    sourceRefs: ['src/platform/Scoring/CommodityResearchModelContracts.ts'],
    benchmark: { runtimeCostClass: 'MEDIUM', evidenceStrength: 3, integrationComplexity: 4, providerLatencyMeasured: false },
  },
  {
    id: 'market-sentiment-evidence',
    conceptName: 'Data Authority & Evidence',
    toolName: 'AI Market Sentiment Evidence Projection',
    kind: 'ANALYSIS',
    assetClasses: ['crypto', 'stock', 'forex', 'index', 'commodity', 'multi-asset'],
    subclasses: ['Research context only'],
    bestConcept: 'Data Authority & Evidence because every numeric sentiment feature must be separately attested.',
    status: 'RESEARCH_ONLY',
    bindingSequence: evidenceSequence,
    providerApplicationServices: ['News evidence providers', 'Financial-NLP adapter', 'SentimentEvidenceProjection'],
    storageModels: ['Sentiment feature attestations', 'Evidence refs', 'Research projection'],
    uiFlow: ['News/social evidence', 'Feature attestation', 'Sentiment research evaluator', 'Read-only sentiment UI'],
    scoringModel: 'crypto-sentiment-research · research context only',
    formula: 'A score is emitted only when every required feature is attested and fresh; no default/neutral replacement score is allowed.',
    sourceRefs: ['src/platform/Scoring/SentimentEvidenceProjection.ts', 'src/platform/Scoring/SentimentNewsFeatureEvidenceAdapter.ts'],
    benchmark: { runtimeCostClass: 'MEDIUM', evidenceStrength: 4, integrationComplexity: 4, providerLatencyMeasured: false },
  },
  {
    id: 'macro-risk-regime',
    conceptName: 'Data Authority & Evidence',
    toolName: 'Macro Yield-Curve Risk Regime',
    kind: 'ANALYSIS',
    assetClasses: ['multi-asset'],
    subclasses: ['Cross-asset macro context'],
    bestConcept: 'Data Authority & Evidence; macro context must never masquerade as an execution price or asset score.',
    status: 'CONTEXT_ONLY',
    bindingSequence: evidenceSequence,
    providerApplicationServices: ['FRED macro evidence adapter'],
    storageModels: ['MacroRiskRegimeEvidence', 'Evidence IDs'],
    uiFlow: ['FRED DGS2/DGS10 evidence', 'buildMacroRiskRegime', 'Context projection', 'UI'],
    scoringModel: 'macro-risk-regime/1.1.0 context contract',
    formula: 'spread10y2yBps = (DGS10 - DGS2) × 100; < -10 = inverted, > 10 = normal, otherwise flat. No asset score.',
    sourceRefs: ['src/services/macroRiskRegime.ts', 'src/services/macroRateEvidence.ts'],
    benchmark: { runtimeCostClass: 'LOW', evidenceStrength: 5, integrationComplexity: 2, providerLatencyMeasured: false },
  },
  {
    id: 'cross-asset-ranking',
    conceptName: 'Data Authority & Evidence',
    toolName: 'Cross-Asset Ranking',
    kind: 'RANKING',
    assetClasses: ['multi-asset'],
    subclasses: ['Comparable canonical-score cohorts', 'Verified normalized-score cohorts'],
    bestConcept: 'Data Authority & Evidence; ranking is downstream of canonical score/evidence lineage and never invents comparability.',
    status: 'CANONICAL',
    bindingSequence: ['CanonicalScoreResult', 'Governance eligibility', 'Comparability evidence', 'Cohort builder', 'Descending ranking', 'Ranking UI'],
    providerApplicationServices: ['ScoringDispatcher outputs', 'CrossAssetRanking'],
    storageModels: ['Canonical score lineage', 'Comparability evidence', 'Ranking projection'],
    uiFlow: ['Canonical scores', 'rankCanonicalUniverse', 'RankingBoard'],
    scoringModel: 'cross-asset-ranking contract',
    formula: 'Candidates are grouped only by verified comparability cohort and sorted descending by rankingValue; ties are deterministic by assetId.',
    sourceRefs: ['src/platform/Ranking/CrossAssetRanking.ts'],
    benchmark: { runtimeCostClass: 'LOW', evidenceStrength: 5, integrationComplexity: 3, providerLatencyMeasured: false },
  },
  {
    id: 'deterministic-portfolio-allocation',
    conceptName: 'Individual',
    toolName: 'Deterministic Portfolio Allocator',
    kind: 'PORTFOLIO',
    assetClasses: ['portfolio', 'multi-asset'],
    subclasses: ['Research/Paper long-only unlevered allocation'],
    bestConcept: 'Individual governed allocation contract consuming external target weights; do not derive weights directly from scores.',
    status: 'CANONICAL',
    bindingSequence: ['Governed target weights', 'Portfolio evidence', 'Policy validation', 'Deterministic fixed-point allocation', 'Risk/Compliance handoff', 'Portfolio UI'],
    providerApplicationServices: ['DeterministicPortfolioAllocator', 'Risk/Compliance gate downstream'],
    storageModels: ['Portfolio allocation proposal', 'Input/output hashes', 'Evidence refs'],
    uiFlow: ['Governed targets', 'evaluateDeterministicPortfolioAllocation', 'Proposal', 'Risk/Compliance', 'Portfolio UI'],
    scoringModel: 'allocation contract; not a score-derived optimizer',
    formula: 'targetNotional = totalEquity × targetWeightBps / 10000; rebalance only when absolute drift reaches policy threshold; cash reserve is derived.',
    sourceRefs: ['src/platform/FinTechCore/Portfolio/DeterministicPortfolioAllocator.ts'],
    benchmark: { runtimeCostClass: 'LOW', evidenceStrength: 5, integrationComplexity: 3, providerLatencyMeasured: false },
  },
  {
    id: 'individual-bond-scoring-draft',
    conceptName: 'Individual',
    toolName: 'Individual Bond Scoring Proposal',
    kind: 'SCORING',
    assetClasses: ['bond'],
    subclasses: ['Individual government/corporate bonds'],
    bestConcept: 'Individual evidence contract, but keep disabled until formal review, Golden Dataset backtest and explicit promotion.',
    status: 'DISABLED',
    bindingSequence: evidenceSequence,
    providerApplicationServices: ['Bond evidence adapter', 'Macro reference evidence'],
    storageModels: ['Bond feature candidate', 'Draft weight proposal', 'Review evidence'],
    uiFlow: ['Bond evidence', 'Draft feature contract', 'Review/backtest only', 'No productive route'],
    scoringModel: 'bond-scoring-weights-proposal/0.1.0-draft',
    formula: 'Draft only: duration sensitivity 22% + yield attractiveness 18% + credit quality 20% + liquidity 12% + momentum 12% + curve/regime 10% + currency risk 6%. Productive scoring is disabled.',
    sourceRefs: ['src/services/bondScoringWeightsProposal.ts', 'docs/adr/ADR-0022-bond-scoring-evidence-architecture.md'],
    benchmark: { runtimeCostClass: 'MEDIUM', evidenceStrength: 2, integrationComplexity: 4, providerLatencyMeasured: false },
  },
  {
    id: 'altcoin-pattern-research',
    conceptName: 'Individual',
    toolName: 'Altcoin Pattern Research Scorer',
    kind: 'ANALYSIS',
    assetClasses: ['crypto'],
    subclasses: ['Altcoin pattern research'],
    bestConcept: 'Individual OHLC/pattern evidence pipeline joined only as research context until independently validated.',
    status: 'RESEARCH_ONLY',
    bindingSequence: evidenceSequence,
    providerApplicationServices: ['Market history provider', 'PatternSignalResolver', 'AltcoinPatternResearchScorer'],
    storageModels: ['Pattern evidence', 'Research signal'],
    uiFlow: ['OHLC/history evidence', 'Pattern resolver', 'Research scorer', 'UI context'],
    scoringModel: 'FinTechCore altcoin pattern research',
    formula: 'Deterministic research signal from evidenced pattern inputs; must not be double-counted with momentum/breakout factors.',
    sourceRefs: ['src/platform/FinTechCore/Modules/Crypto/Pattern/AltcoinPatternResearchScorer.ts', 'src/platform/FinTechCore/Modules/Crypto/Pattern/PatternSignalResolver.ts'],
    benchmark: { runtimeCostClass: 'LOW', evidenceStrength: 3, integrationComplexity: 3, providerLatencyMeasured: false },
  },
  {
    id: 'market-screener-projection',
    conceptName: 'Hybrid',
    toolName: 'Profi Market Screener',
    kind: 'ANALYSIS',
    assetClasses: ['multi-asset'],
    subclasses: ['Verified multi-asset screening'],
    bestConcept: 'Hybrid consumer: live discovery + canonical score/evidence projection; no route-local score generation.',
    status: 'CANONICAL',
    bindingSequence: ['Asset discovery', 'Verified market/evidence data', 'Canonical score/ranking', 'Screen filters', 'Market Screener UI'],
    providerApplicationServices: ['MarketDataGateway', 'ScoringDispatcher', 'CrossAssetRanking'],
    storageModels: ['Verified asset catalog', 'Canonical score projection'],
    uiFlow: ['Verified assets', 'Canonical score/ranking', 'MarketScreener'],
    scoringModel: 'No independent formula; consumes canonical scores and verified evidence.',
    formula: 'Filter/sort projection only. Any score displayed must originate from the canonical scoring path.',
    sourceRefs: ['src/components/MarketScreener.tsx', 'src/app/public/PublicAnalysisWorkbench.tsx'],
    benchmark: { runtimeCostClass: 'LOW', evidenceStrength: 5, integrationComplexity: 2, providerLatencyMeasured: false },
  },
  {
    id: 'crypto-momentum-research',
    conceptName: 'Data Authority & Evidence',
    toolName: 'Crypto Momentum Research',
    kind: 'ANALYSIS',
    assetClasses: ['crypto'],
    subclasses: ['Crypto momentum / flow context'],
    bestConcept: 'Data Authority & Evidence; every return/flow/liquidity input remains explicit and missing values are never replaced by neutral defaults.',
    status: 'RESEARCH_ONLY',
    bindingSequence: evidenceSequence,
    providerApplicationServices: ['MarketDataHistoryGateway', 'Flow/Open-Interest evidence adapters', 'CryptoOrchestratorResearchModels'],
    storageModels: ['MomentumResearchInput', 'Research feature attestations', 'Research assessment'],
    uiFlow: ['Verified returns/flow evidence', 'evaluateMomentumResearch', 'Research-only projection', 'UI'],
    scoringModel: 'crypto-momentum-research/0.1.0',
    formula: 'trend = 25% tanh(1h return×20) + 20% tanh(4h×12) + 20% tanh(1d×8) + 20% tanh(trendStrength) + 15% tanh(relativeStrength); flow uses renormalized 35/25/20/20 weights; raw = 62% trend + 38% flow minus overheat penalties; logistic projection to 0..100. scoreEligible=false.',
    sourceRefs: ['src/platform/Scoring/CryptoOrchestratorResearchModels.ts'],
    benchmark: { runtimeCostClass: 'LOW', evidenceStrength: 4, integrationComplexity: 4, providerLatencyMeasured: false },
  },
  {
    id: 'crypto-regime-research',
    conceptName: 'Data Authority & Evidence',
    toolName: 'Crypto Regime Research',
    kind: 'ANALYSIS',
    assetClasses: ['crypto'],
    subclasses: ['Crypto market-regime context'],
    bestConcept: 'Data Authority & Evidence; regime classifications consume evidenced momentum, sentiment, liquidity, flow and volatility context.',
    status: 'RESEARCH_ONLY',
    bindingSequence: evidenceSequence,
    providerApplicationServices: ['Crypto Momentum Research', 'Sentiment evidence projection', 'Liquidity/flow evidence adapters', 'CryptoOrchestratorResearchModels'],
    storageModels: ['RegimeResearchInput', 'Research regime assessment', 'Evidence refs'],
    uiFlow: ['Momentum + sentiment + flow evidence', 'evaluateRegimeResearch', 'Research regime context', 'UI'],
    scoringModel: 'crypto-regime-research/0.1.0',
    formula: 'Deterministic threshold classifier: liquidityChange < -0.30 => STRESS/ILLIQUID; momentum>70 + sentiment>65 + volumeRatio>1.5 + whaleExchangeFlow<0 => BULL; momentum<35 => BEAR; governed volatility threshold may produce HIGH_VOLATILITY. No productive score.',
    sourceRefs: ['src/platform/Scoring/CryptoOrchestratorResearchModels.ts'],
    benchmark: { runtimeCostClass: 'LOW', evidenceStrength: 4, integrationComplexity: 4, providerLatencyMeasured: false },
  },
  {
    id: 'crypto-pattern-confluence-research',
    conceptName: 'Individual',
    toolName: 'Crypto Pattern Confluence Research',
    kind: 'ANALYSIS',
    assetClasses: ['crypto'],
    subclasses: ['Multi-timeframe candlestick/pattern evidence'],
    bestConcept: 'Individual pattern evidence adapter joined to the Data Authority plane; never promote a visual pattern into a canonical asset score.',
    status: 'RESEARCH_ONLY',
    bindingSequence: evidenceSequence,
    providerApplicationServices: ['PatternSignalResolver', 'CryptoOrchestratorResearchModels'],
    storageModels: ['PatternSignalResolution', 'Pattern evidence refs', 'Research assessment'],
    uiFlow: ['OHLC/pattern evidence', 'PatternSignalResolver', 'evaluatePatternConfluenceResearch', 'Research projection', 'UI'],
    scoringModel: 'crypto-pattern-confluence-research/0.1.0',
    formula: 'READY only when at least two same-direction timeframes exist and one confirming timeframe is >=4h; meanPatternQuality is the arithmetic mean of the evidenced same-direction candidates. scoreEligible=false.',
    sourceRefs: ['src/platform/Scoring/CryptoOrchestratorResearchModels.ts', 'src/platform/FinTechCore/Modules/Crypto/Pattern/PatternSignalResolver.ts'],
    benchmark: { runtimeCostClass: 'LOW', evidenceStrength: 4, integrationComplexity: 3, providerLatencyMeasured: false },
  },
  {
    id: 'crypto-signal-fusion-research',
    conceptName: 'Hybrid',
    toolName: 'Crypto Signal Fusion Research',
    kind: 'ANALYSIS',
    assetClasses: ['crypto'],
    subclasses: ['Research-only multi-signal fusion'],
    bestConcept: 'Hybrid evidence fusion after individual signal contracts; explicitly not an order/trade authority.',
    status: 'RESEARCH_ONLY',
    bindingSequence: evidenceSequence,
    providerApplicationServices: ['Crypto Momentum Research', 'Sentiment Research', 'Pattern Confluence Research', 'CryptoOrchestratorResearchModels'],
    storageModels: ['SignalFusionResearchInput', 'Research assessment', 'Evidence refs'],
    uiFlow: ['Research sub-signals', 'evaluateSignalFusionResearch', 'Research trade-context score', 'UI'],
    scoringModel: 'crypto-signal-fusion-research/0.1.0',
    formula: 'researchTradeScore = 30% regimeFit + 25% momentumScore + 20% patternQuality + 15% sentimentScore + 10% executionQuality; source threshold is score>=70 and regimeFit>=60. executionEligible=false.',
    sourceRefs: ['src/platform/Scoring/CryptoOrchestratorResearchModels.ts'],
    benchmark: { runtimeCostClass: 'LOW', evidenceStrength: 4, integrationComplexity: 4, providerLatencyMeasured: false },
  },
  {
    id: 'crypto-kill-switch-research',
    conceptName: 'Individual',
    toolName: 'Crypto Kill-Switch Research Telemetry',
    kind: 'ANALYSIS',
    assetClasses: ['crypto'],
    subclasses: ['Risk telemetry / research defaults'],
    bestConcept: 'Individual risk-telemetry contract; research defaults must never become production risk policy without an owner-approved policy contract.',
    status: 'RESEARCH_ONLY',
    bindingSequence: ['Risk telemetry evidence', 'Input validation', 'Research threshold evaluator', 'Recommended action projection', 'Risk UI'],
    providerApplicationServices: ['CryptoOrchestratorResearchModels', 'Risk telemetry adapters'],
    storageModels: ['KillSwitchResearchInput', 'KillSwitchResearchAssessment', 'Audit evidence refs'],
    uiFlow: ['Telemetry evidence', 'evaluateKillSwitchResearchTelemetry', 'L1-L4 research level', 'Risk UI'],
    scoringModel: 'crypto-kill-switch-telemetry/0.1.0',
    formula: 'Research thresholds include daily loss 2%, session loss 1.25%, consecutive losses 3, order rejects 5%, slippage 12 bps; L4 integrity/config failures outrank L3 provider/venue failures, L2 session conditions and L1 soft-pause conditions. Not production policy.',
    sourceRefs: ['src/platform/Scoring/CryptoOrchestratorResearchModels.ts'],
    benchmark: { runtimeCostClass: 'LOW', evidenceStrength: 3, integrationComplexity: 4, providerLatencyMeasured: false },
  },
  {
    id: 'buffett-value-check',
    conceptName: 'Individual',
    toolName: 'Buffett Value Check',
    kind: 'ANALYSIS',
    assetClasses: ['stock'],
    subclasses: ['Equities with verified stock display/fundamentals; manual scenario assumptions explicitly labelled'],
    bestConcept: 'Individual valuation workflow over Data Authority/Evidence: verified price/fundamentals plus clearly separated manual assumptions.',
    status: 'COMPATIBILITY_ONLY',
    bindingSequence: ['Verified Asset Display / Fundamentals', 'Entitlement gate', 'Evidence / manual assumption separation', 'Graham + DCF valuation', 'Valuation projection', 'UI'],
    providerApplicationServices: ['Verified Asset Display endpoint', 'Warren-Buffett entitlement adapter', 'Financial fundamentals evidence'],
    storageModels: ['Verified display provenance', 'Manual scenario inputs', 'Valuation result'],
    uiFlow: ['Verified stock display', 'Scenario inputs', 'calculateGrahamValue / calculateDcfValue', 'Margin of Safety', 'Buffett Value Check UI'],
    scoringModel: 'Valuation analysis; compatibility consumer, not CanonicalScoreResult',
    formula: 'Graham = EPS × (8.5 + 2g) × bondYieldFactor / aaaBondYield. DCF = sum(projected cash flow per share / (1+r)^year) + terminalPrice/(1+r)^N. Margin of Safety = (consensusValue - marketPrice) / consensusValue × 100.',
    sourceRefs: ['src/components/BuffetValueCheck.tsx', 'docs/frontend/COMPONENT_INVENTORY.md'],
    benchmark: { runtimeCostClass: 'LOW', evidenceStrength: 4, integrationComplexity: 3, providerLatencyMeasured: false },
  },
  {
    id: 'monte-carlo-risk-engine',
    conceptName: 'Individual',
    toolName: 'Monte-Carlo Risk Engine',
    kind: 'ANALYSIS',
    assetClasses: ['portfolio', 'multi-asset'],
    subclasses: ['Scenario simulation with user-selectable expected return/volatility'],
    bestConcept: 'Individual governed simulation contract after verified input sourcing; current UI remains blocked until execution/data authority is fully contracted.',
    status: 'BLOCKED',
    bindingSequence: ['Market/evidence input', 'Entitlement gate', 'Governed simulation parameters', 'Monte-Carlo engine', 'Risk statistics', 'UI'],
    providerApplicationServices: ['Market data endpoint', 'Monte-Carlo entitlement adapter'],
    storageModels: ['Simulation parameters', 'Scenario paths', 'Percentile/VaR result'],
    uiFlow: ['Market data + manual assumptions', 'GBM simulation', '5/50/95 percentile result', 'VaR projection', 'MonteCarloDetailed UI'],
    scoringModel: 'Client-side GBM simulation; BLOCKED_INVALID_OR_MISSING_CONTRACT',
    formula: 'Price_t = Price_(t-1) × exp((r - 0.5σ²)Δt + σW√Δt); final path percentiles 5/50/95; VaR95 = initialCapital - 5th-percentile final value. Current random-normal approximation and execution boundary require owner validation.',
    sourceRefs: ['src/components/MonteCarloDetailed.tsx', 'docs/frontend/COMPONENT_INVENTORY.md'],
    benchmark: { runtimeCostClass: 'HIGH', evidenceStrength: 2, integrationComplexity: 4, providerLatencyMeasured: false },
  },
  {
    id: 'quant-backtest-engine',
    conceptName: 'Hybrid',
    toolName: 'Quantitative Backtest Engine',
    kind: 'ANALYSIS',
    assetClasses: ['crypto', 'stock', 'forex', 'commodity', 'multi-asset'],
    subclasses: ['Historical strategy backtesting'],
    bestConcept: 'Hybrid: canonical historical data/evidence plus protected execution; current compatibility history boundary must converge before canonical status.',
    status: 'COMPATIBILITY_ONLY',
    bindingSequence: ['Asset discovery', 'Backtest entitlement', 'Historical data boundary', 'Strategy calculation', 'Risk/performance metrics', 'Report/UI'],
    providerApplicationServices: ['/api/backtest-history compatibility boundary', 'Backtest entitlement adapter'],
    storageModels: ['Historical close series', 'Trade ledger', 'Backtest metrics/report'],
    uiFlow: ['Historical closes', 'calculateBacktestOnRealData', 'Strategy vs Buy&Hold', 'Sharpe/Max Drawdown', 'Backtest UI/PDF'],
    scoringModel: 'Historical strategy evaluator; compatibility boundary',
    formula: 'Strategy value is calculated from historical closes and configured strategy rules; return = (final-initial)/initial; Max Drawdown derives from running peak; Sharpe is derived from strategy return/risk statistics. No synthetic history may be presented as verified evidence.',
    sourceRefs: ['src/components/BacktestEngine.tsx', 'docs/frontend/COMPONENT_INVENTORY.md'],
    benchmark: { runtimeCostClass: 'MEDIUM', evidenceStrength: 3, integrationComplexity: 4, providerLatencyMeasured: false },
  },
  {
    id: 'portfolio-backtester',
    conceptName: 'Hybrid',
    toolName: 'Portfolio Allocation Backtester',
    kind: 'PORTFOLIO',
    assetClasses: ['portfolio', 'multi-asset'],
    subclasses: ['Weighted multi-asset portfolio vs equal-weight benchmark'],
    bestConcept: 'Hybrid with canonical history/evidence and protected backtest execution; preserve explicit weights and provider/source lineage.',
    status: 'COMPATIBILITY_ONLY',
    bindingSequence: ['Portfolio weights', 'Backtest entitlement', 'Per-asset history evidence', 'Aligned time series', 'Portfolio/benchmark metrics', 'Portfolio UI'],
    providerApplicationServices: ['/api/backtest-history compatibility boundary', '/api/portfolio-review', 'Backtest entitlement adapter'],
    storageModels: ['Portfolio allocation', 'Aligned price history', 'Performance/risk metrics', 'AI review evidence'],
    uiFlow: ['Weights + histories', 'calculateForRange', 'Portfolio vs equal-weight benchmark', 'Risk metrics', 'PortfolioBacktester UI'],
    scoringModel: 'Historical portfolio backtest; compatibility boundary',
    formula: 'portfolioValue_t = Σ(initialCapital × weight_i × price_i,t / firstPrice_i); benchmark uses 1/N weights. Volatility = stdev(dailyReturns)×√365×100. Sharpe = (CAGR - 2.5%) / annualized volatility. Max Drawdown uses running peak.',
    sourceRefs: ['src/components/PortfolioBacktester.tsx', 'docs/frontend/COMPONENT_INVENTORY.md'],
    benchmark: { runtimeCostClass: 'MEDIUM', evidenceStrength: 3, integrationComplexity: 4, providerLatencyMeasured: false },
  },
  {
    id: 'portfolio-performance-legacy',
    conceptName: 'Individual',
    toolName: 'Portfolio Performance Legacy Dashboard',
    kind: 'ANALYSIS',
    assetClasses: ['portfolio'],
    subclasses: ['Legacy synthetic portfolio performance projection'],
    bestConcept: 'Individual verified NAV/performance evidence contract is required; current synthetic generator must remain blocked.',
    status: 'BLOCKED',
    bindingSequence: ['Verified NAV/performance evidence REQUIRED', 'Provenance/Freshness REQUIRED', 'Risk metric calculation REQUIRED', 'Performance projection', 'Portfolio UI'],
    providerApplicationServices: ['Future owner-authoritative portfolio/NAV adapter'],
    storageModels: ['Verified NAV series REQUIRED', 'Risk metric lineage REQUIRED'],
    uiFlow: ['Current synthetic series BLOCKED', 'Owner-authoritative metrics required', 'Portfolio Performance UI'],
    scoringModel: 'BLOCKED legacy synthetic performance',
    formula: 'Current component synthesizes value waves via sin/cos functions and hard-codes timeframe Sharpe, drawdown, volatility and VaR. These values are not evidence-backed and must not be treated as benchmark truth.',
    sourceRefs: ['src/components/PortfolioPerformance.tsx', 'docs/frontend/COMPONENT_INVENTORY.md'],
    benchmark: { runtimeCostClass: 'LOW', evidenceStrength: 1, integrationComplexity: 3, providerLatencyMeasured: false },
  },
  {
    id: 'legacy-screener',
    conceptName: 'Hybrid',
    toolName: 'Legacy Screener',
    kind: 'ANALYSIS',
    assetClasses: ['multi-asset'],
    subclasses: ['Legacy multi-asset screening simulation'],
    bestConcept: 'Hybrid canonical MarketScreener path should supersede this route-local simulation; no local pseudo-score or hard-coded pattern authority.',
    status: 'BLOCKED',
    bindingSequence: ['Canonical asset discovery REQUIRED', 'Verified score/evidence REQUIRED', 'Canonical ranking/filtering REQUIRED', 'Screener UI'],
    providerApplicationServices: ['MarketDataGateway', 'ScoringDispatcher', 'CrossAssetRanking'],
    storageModels: ['Canonical score projection REQUIRED'],
    uiFlow: ['Current pseudo-score/pattern simulation BLOCKED', 'Canonical screener replacement', 'UI'],
    scoringModel: 'Legacy route-local simulation — blocked',
    formula: 'Current component applies deterministic symbol pseudo-random price/score offsets, hard-coded pattern labels and can force Bullish Engulfing to score 85. This is not canonical scoring evidence.',
    sourceRefs: ['src/components/Screener.tsx', 'docs/frontend/COMPONENT_INVENTORY.md'],
    benchmark: { runtimeCostClass: 'LOW', evidenceStrength: 1, integrationComplexity: 2, providerLatencyMeasured: false },
  },
  {
    id: 'charts-technical-analysis-legacy',
    conceptName: 'Hybrid',
    toolName: 'Charts Technical Analysis',
    kind: 'ANALYSIS',
    assetClasses: ['crypto', 'stock', 'forex', 'index', 'commodity'],
    subclasses: ['Technical chart indicators and legacy chart-scoring consumer'],
    bestConcept: 'Hybrid verified OHLCV/history + canonical scoring projection; simulation-only /api/charts-scoring must not be promoted.',
    status: 'BLOCKED',
    bindingSequence: ['Verified OHLCV/history REQUIRED', 'Technical indicator calculation', 'Canonical score/evidence REQUIRED', 'Chart projection', 'UI'],
    providerApplicationServices: ['/api/backtest-history compatibility boundary', '/api/charts-scoring NON_PRODUCTION_SIMULATION'],
    storageModels: ['Historical OHLCV', 'Indicator series', 'Canonical score projection REQUIRED'],
    uiFlow: ['History', 'MA/Bollinger/RSI', 'Simulation-only score boundary BLOCKED', 'Charts UI'],
    scoringModel: '/api/charts-scoring = NON_PRODUCTION_SIMULATION',
    formula: 'Client computes moving averages, Bollinger volatility bands and RSI from history; any displayed score must move to CanonicalScoreResult. No simulation-only score is benchmark truth.',
    sourceRefs: ['src/components/Charts.tsx', 'docs/frontend/COMPONENT_INVENTORY.md'],
    benchmark: { runtimeCostClass: 'MEDIUM', evidenceStrength: 2, integrationComplexity: 4, providerLatencyMeasured: false },
  },
  {
    id: 'heatmap-creator-legacy',
    conceptName: 'Individual',
    toolName: 'Market Sentiment Heatmap Creator',
    kind: 'ANALYSIS',
    assetClasses: ['crypto', 'stock', 'forex', 'multi-asset'],
    subclasses: ['Legacy custom heatmap/pattern sandbox'],
    bestConcept: 'Individual sandbox may remain only with explicit scenario labels; productive heatmap requires canonical evidence and no preset financial truth.',
    status: 'BLOCKED',
    bindingSequence: ['Verified market/evidence REQUIRED', 'Governed sentiment/pattern features REQUIRED', 'Heatmap projection', 'UI'],
    providerApplicationServices: ['MarketDataGateway', 'Sentiment/Pattern evidence adapters REQUIRED'],
    storageModels: ['Scenario-only local configuration', 'Verified evidence projection REQUIRED'],
    uiFlow: ['Current preset/pseudo-derived nodes BLOCKED', 'Governed evidence projection required', 'Heatmap UI'],
    scoringModel: 'Legacy preset/pseudo sentiment heatmap — blocked',
    formula: 'Current API conversion derives bullish = clamp(50 + change24h×5 + (score-5)×3), estimates volume from marketCap×0.05 and assigns patterns by symbol hash; defaults contain preset bullish/bearish values. Not canonical evidence.',
    sourceRefs: ['src/components/HeatmapCreator.tsx', 'docs/frontend/COMPONENT_INVENTORY.md'],
    benchmark: { runtimeCostClass: 'LOW', evidenceStrength: 1, integrationComplexity: 3, providerLatencyMeasured: false },
  },
  {
    id: 'realtime-risk-assessment-disabled',
    conceptName: 'Individual',
    toolName: 'Real-Time Risk Assessment / VaR',
    kind: 'ANALYSIS',
    assetClasses: ['portfolio', 'multi-asset'],
    subclasses: ['Archived/deactivated risk center'],
    bestConcept: 'Individual verified risk-evidence contract only after explicit owner reactivation.',
    status: 'DISABLED',
    bindingSequence: ['Owner reactivation REQUIRED', 'Verified portfolio exposure', 'Governed risk model', 'Risk evidence', 'UI'],
    providerApplicationServices: ['None active; owner resolution required'],
    storageModels: ['No active risk result model'],
    uiFlow: ['Component currently returns null', 'No productive route'],
    scoringModel: 'Disabled archived module',
    formula: 'No active formula. The current component returns null and must not be inferred as a live VaR engine.',
    sourceRefs: ['src/components/RealTimeRiskAssessment.tsx', 'docs/frontend/COMPONENT_INVENTORY.md'],
    benchmark: { runtimeCostClass: 'LOW', evidenceStrength: 1, integrationComplexity: 5, providerLatencyMeasured: false },
  },
  {
    id: 'favorite-asset-pattern-slots',
    conceptName: 'Individual',
    toolName: 'Favorite Asset Live Pattern Slots',
    kind: 'ANALYSIS',
    assetClasses: ['crypto'],
    subclasses: ['Binance spot symbols with 1h/4h klines'],
    bestConcept: 'Individual read-only pattern evidence path; migrate browser-direct provider access behind the governed provider/evidence boundary.',
    status: 'COMPATIBILITY_ONLY',
    bindingSequence: ['Binance Kline provider', 'OHLC validation', 'Candlestick pattern detector', 'Read-only pattern projection', 'UI'],
    providerApplicationServices: ['Current browser-direct Binance /api/v3/klines', 'Future MarketDataGateway/history adapter'],
    storageModels: ['Ephemeral OHLC candles', 'DetectedPattern results', 'Local favorite slots only'],
    uiFlow: ['1h/4h Binance klines', 'detectActivePatterns', 'Pattern badges', 'Favorite slots UI'],
    scoringModel: 'Read-only pattern analysis; no canonical score impact',
    formula: 'Candlestick formations are detected from real OHLC candles; pattern output is context only and explicitly has no influence on CanonicalScoreResult.',
    sourceRefs: ['src/components/FavoriteAssetPatternSlots.tsx', 'src/services/candlestickPatterns.ts', 'docs/frontend/COMPONENT_INVENTORY.md'],
    benchmark: { runtimeCostClass: 'LOW', evidenceStrength: 3, integrationComplexity: 3, providerLatencyMeasured: false },
  },
  {
    id: 'asset-universe-sandbox-legacy',
    conceptName: 'Individual',
    toolName: 'Asset Universe What-If Scoring Sandbox',
    kind: 'ANALYSIS',
    assetClasses: ['crypto', 'stock', 'forex', 'index', 'commodity', 'multi-asset'],
    subclasses: ['Legacy slider-configured model sandbox'],
    bestConcept: 'Individual what-if sandbox may visualize owner-supplied contracts only; current hard-coded models/example scores must not represent production scoring.',
    status: 'BLOCKED',
    bindingSequence: ['Canonical model descriptors REQUIRED', 'Scenario inputs', 'Sandbox calculation', 'Explicit non-production result', 'UI'],
    providerApplicationServices: ['ScoringModelRegistry projection REQUIRED', 'No route-local model authority'],
    storageModels: ['Scenario-only values', 'Canonical model metadata REQUIRED'],
    uiFlow: ['Current hard-coded configs/examples BLOCKED', 'Registry-driven model graph required', 'Asset Universe UI'],
    scoringModel: 'Legacy hard-coded what-if formulas — blocked as production authority',
    formula: 'Current component contains route-local formulas and example scores for crypto/equities/indices/forex plus a commodity canonical formula. Only the commodity formula may match the canonical contract; all model metadata must instead derive from FINTECH registry/contracts.',
    sourceRefs: ['src/components/AssetUniverseDashboard.tsx', 'docs/frontend/COMPONENT_INVENTORY.md'],
    benchmark: { runtimeCostClass: 'LOW', evidenceStrength: 1, integrationComplexity: 3, providerLatencyMeasured: false },
  },
  {
    id: 'enterprise-scorer-workbench',
    conceptName: 'Data Authority & Evidence',
    toolName: 'Enterprise Scorer Workbench',
    kind: 'ANALYSIS',
    assetClasses: ['crypto', 'stock', 'forex', 'index', 'multi-asset'],
    subclasses: ['Canonical score/evidence consumer; productive bonds excluded'],
    bestConcept: 'Data Authority & Evidence consumer only: model/version/evidence must come from canonical endpoints and registry/dispatcher lineage.',
    status: 'CANONICAL',
    bindingSequence: ['Evidence/provenance endpoint', 'Canonical score endpoint', 'CanonicalScoreResult', 'Visualization view model', 'Enterprise Scorer UI'],
    providerApplicationServices: ['/api/crypto/score', '/api/registry/assets/:symbol/verified-score', 'ScoringDispatcher'],
    storageModels: ['CanonicalScoreResult', 'Provenance entries', 'Evidence IDs'],
    uiFlow: ['Canonical endpoint', 'buildCryptoView/buildTraditionalView', 'Evidence/score visualization', 'Enterprise Scorer UI'],
    scoringModel: 'Projection-only; model selected by ScoringModelRegistry/ScoringDispatcher',
    formula: 'No independent UI formula. The workbench renders the canonical score and factor/evidence lineage supplied by the active governed model.',
    sourceRefs: ['src/features/crypto/ui/CryptoScoringEnterprise.tsx', 'docs/frontend/COMPONENT_INVENTORY.md'],
    benchmark: { runtimeCostClass: 'LOW', evidenceStrength: 5, integrationComplexity: 2, providerLatencyMeasured: false },
  },
  {
    id: 'raw-materials-dashboard',
    conceptName: 'Data Authority & Evidence',
    toolName: 'Raw Materials Dashboard',
    kind: 'ANALYSIS',
    assetClasses: ['commodity'],
    subclasses: ['Commodity canonical market score + separated research projections'],
    bestConcept: 'Data Authority & Evidence; canonical commodity market score and research/challenger projections must remain visually and contractually separated.',
    status: 'CANONICAL',
    bindingSequence: ['Commodity evidence provider', 'CommodityMarketEvidence', 'Canonical commodity scorer', 'Separated research projections', 'Raw Materials UI'],
    providerApplicationServices: ['Commodity history provider', 'ScoringDispatcher', 'Commodity research evaluators'],
    storageModels: ['CommodityMarketEvidence', 'CanonicalScoreResult', 'Research assessment'],
    uiFlow: ['Verified commodity evidence', 'Canonical score + research separation', 'RawMaterialsDashboard'],
    scoringModel: 'commodity-evidence-scoring/1.0.0 canonical + research-only challengers',
    formula: 'Canonical score remains trend 30% + momentum 25% + breakout_quality 20% + volatility_quality 25%; category research models must never be merged into that canonical score without promotion.',
    sourceRefs: ['src/features/commodities/ui/RawMaterialsDashboard.tsx', 'src/services/commodityEvidenceScoring.ts', 'docs/frontend/COMPONENT_INVENTORY.md'],
    benchmark: { runtimeCostClass: 'LOW', evidenceStrength: 5, integrationComplexity: 3, providerLatencyMeasured: false },
  },

]);

export function validateAnalysisConnectionContracts(
  contracts: readonly AnalysisConnectionContract[] = ANALYSIS_CONNECTION_CONTRACTS,
): readonly string[] {
  const errors: string[] = [];
  const ids = new Set<string>();

  for (const contract of contracts) {
    if (ids.has(contract.id)) errors.push('duplicate-id:' + contract.id);
    ids.add(contract.id);

    if (contract.assetClasses.length === 0) errors.push('missing-asset-class:' + contract.id);
    if (contract.bindingSequence.length < 3) errors.push('binding-sequence-too-short:' + contract.id);
    if (contract.providerApplicationServices.length === 0) errors.push('missing-provider-service:' + contract.id);
    if (contract.storageModels.length === 0) errors.push('missing-storage-model:' + contract.id);
    if (contract.uiFlow.length === 0) errors.push('missing-ui-flow:' + contract.id);
    if (!contract.formula.trim()) errors.push('missing-formula:' + contract.id);
    if (contract.sourceRefs.length === 0) errors.push('missing-source-ref:' + contract.id);

    if ((contract.status === 'DISABLED' || contract.status === 'BLOCKED') && /CANONICAL/i.test(contract.scoringModel)) {
      errors.push('nonproductive-contract-claims-canonical-model:' + contract.id);
    }
  }

  return Object.freeze(errors);
}
