import fs from 'node:fs';
import { execFileSync } from 'node:child_process';
function fail(message){process.stderr.write(`PUBLIC_READINESS_FAIL: ${message}\n`);process.exitCode=1;}
const read=(path)=>fs.readFileSync(path,'utf8');
for(const path of ['.github/CODEOWNERS','.github/SECURITY.md','.github/FUNDING.yml','LICENSE','.gitignore'])if(!fs.existsSync(path))fail(`required repository-safety file missing: ${path}`);
if(fs.existsSync('.github/CODEOWNERS')&&!/^\*\s+@SvenKulessa\s*$/m.test(read('.github/CODEOWNERS')))fail('CODEOWNERS must retain the catch-all Human Owner mapping');
if(fs.existsSync('.github/FUNDING.yml')&&!/^github:\s*\[SvenKulessa\]\s*$/m.test(read('.github/FUNDING.yml')))fail('FUNDING.yml must point only to the declared Human Owner GitHub Sponsors identity');
if(fs.existsSync('.gitignore')&&!/^\.env\*\s*$/m.test(read('.gitignore')))fail('.gitignore must deny tracked .env variants by default');
const tracked=execFileSync('git',['ls-files'],{encoding:'utf8'}).split(/\r?\n/).filter(Boolean);const forbidden=tracked.filter((path)=>path!=='.env.example'&&path!=='server/_.env.example'&&/(^|\/)(?:\.env(?:\..+)?|id_(?:rsa|dsa|ecdsa|ed25519)|[^/]+\.(?:pem|p12|pfx))$/i.test(path));if(forbidden.length)fail(`tracked credential-like files require removal before public visibility: ${forbidden.join(', ')}`);
for(const path of tracked.filter((p)=>p.startsWith('.github/workflows/')&&/\.ya?ml$/i.test(p))){const yaml=read(path);if(/^\s{0,2}pull_request_target\s*:/m.test(yaml))fail(`public-fork unsafe pull_request_target trigger detected: ${path}`);for(const match of yaml.matchAll(/^\s*-?\s*uses:\s*([^\s#]+).*$/gm)){const ref=match[1].replace(/^['"]|['"]$/g,'');if(ref.startsWith('./')||ref.startsWith('docker://'))continue;const at=ref.lastIndexOf('@');if(at<1||!/^[0-9a-f]{40}$/i.test(ref.slice(at+1)))fail(`external Action is not pinned to an immutable full commit SHA: ${path}: ${ref}`);}}
if(process.exitCode)process.exit(process.exitCode);process.stdout.write(`${JSON.stringify({status:'PASS',state:'PUBLIC_VISIBILITY_HELD_FOR_HISTORY_AND_ACTIONS_DISCLOSURE_REVIEW',repository:'capital-ai-online/Finance',currentTreeControls:{codeownersCatchAll:true,securityPolicy:true,fundingConfig:true,envFilesDeniedByDefault:true,pullRequestTargetForbidden:true,externalActionsFullShaPinned:true},humanGatesStillRequired:['Review historical Git/secret-scanning evidence before visibility change','Review historical GitHub Actions logs because they become public','Confirm that keeping the proprietary UNLICENSED source-public model is intentional or choose a license separately','Perform the repository visibility change only after live post-merge ruleset/security readback'],visibilityMutationPerformed:false},null,2)}\n`);
