import type { VocabularyCategory, VocabularyConcept } from '../Domain/VocabularyConcept';

const authorityRefs = ['ESS-0017', 'ESS-0017-CONTRACTS'];
const vocabularyAuthority = ['ADR-0078'];

function documentationConcept(
  id: string,
  canonicalCodeTerm: string,
  displayNameDE: string,
  displayNameEN: string,
  definitionDE: string,
  definitionEN: string,
  category: VocabularyCategory,
  aliases: string[],
  traceabilityReferences: string[],
  adrReferences: string[] = [],
): VocabularyConcept {
  return {
    id,
    canonicalCodeTerm,
    displayNameDE,
    displayNameEN,
    definitionDE,
    definitionEN,
    aliases,
    forbiddenTerms: [],
    category,
    status: 'approved',
    version: '1.0.0',
    essReferences: authorityRefs,
    adrReferences: Array.from(new Set([...vocabularyAuthority, ...adrReferences])),
    traceabilityReferences,
  };
}

/**
 * Stable technical vocabulary mined from the repository-wide Markdown/README inventory.
 *
 * The source documents remain authoritative for their own subject matter. These concepts are
 * terminology projections only and do not promote a README, ADR title, runbook, or archived
 * document into a new execution authority.
 */
export const documentationDerivedConcepts: VocabularyConcept[] = [
  documentationConcept(
    'VOC-DOCMIN-0001',
    'Idempotency',
    'Idempotenz',
    'Idempotency',
    'Eigenschaft einer Operation oder Ereignisverarbeitung, bei wiederholter Ausführung mit derselben Identität keinen zusätzlichen fachlichen Effekt zu erzeugen.',
    'Property of an operation or event handler that repeated execution with the same identity does not create an additional domain effect.',
    'architecture',
    ['idempotent', 'idempotente Verarbeitung'],
    ['src/platform/EventMesh/README.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0002',
    'EventOrdering',
    'Ereignisreihenfolge',
    'Event ordering',
    'Kontrollierte Reihenfolge zusammengehöriger Ereignisse, damit spätere oder veraltete Zustände nicht unbemerkt vor gültigen Vorgängern verarbeitet werden.',
    'Controlled ordering of related events so later or stale states are not silently processed ahead of valid predecessors.',
    'architecture',
    ['Event-Reihenfolge', 'Ordering'],
    ['src/platform/EventMesh/README.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0003',
    'EventReplay',
    'Event-Replay',
    'Event replay',
    'Kontrolliertes erneutes Verarbeiten bereits erfasster Ereignisse unter Replay-, Idempotenz- und Stale-State-Schutzregeln.',
    'Controlled reprocessing of previously captured events under replay, idempotency, and stale-state safeguards.',
    'architecture',
    ['Replay', 'Ereignis-Replay'],
    ['src/platform/EventMesh/README.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0004',
    'ReliabilityEvidence',
    'Reliability Evidence',
    'Reliability evidence',
    'Nachweisbare Betriebsdaten über Zuverlässigkeit und Verarbeitung einer technischen Komponente oder Ereigniskette.',
    'Provable operational data about the reliability and processing behavior of a technical component or event chain.',
    'documentation',
    ['Zuverlässigkeitsnachweis'],
    ['src/platform/EventMesh/README.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0005',
    'Observability',
    'Observability',
    'Observability',
    'Beobachtbarkeit eines laufenden Systems über strukturierte Betriebsdaten wie Telemetrie, Logs, Metriken und Tracing-Signale, ohne fachliche Audit-Evidence zu ersetzen.',
    'Ability to observe a running system through structured operational data such as telemetry, logs, metrics, and tracing signals without replacing domain audit evidence.',
    'platform',
    ['Beobachtbarkeit'],
    ['docs/adr/ADR-0056-observability-telemetry-baseline.md', 'src/platform/Telemetry/README.md'],
    ['ADR-0056'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0006',
    'OperationalTelemetry',
    'Operational Telemetry',
    'Operational telemetry',
    'Vendor-neutrale Betriebs-Telemetrie für Laufzeit-, Request-, Trace-, Outcome- und Dauerinformationen; revisionsrelevante Audit-Evidence bleibt davon getrennt.',
    'Vendor-neutral operational telemetry for runtime, request, trace, outcome, and duration information; audit-relevant evidence remains separate.',
    'platform',
    ['Betriebs-Telemetrie'],
    ['docs/adr/ADR-0056-observability-telemetry-baseline.md', 'src/platform/Telemetry/README.md'],
    ['ADR-0056'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0007',
    'EdgeTrust',
    'Edge Trust',
    'Edge trust',
    'Vertrauensbewertung und Korrelation von Request-Signalen an der Edge-Grenze, bevor solche Signale als belastbarer Anwendungskontext verwendet werden.',
    'Trust assessment and correlation of request signals at the edge boundary before those signals are used as reliable application context.',
    'iam',
    ['Edge-Vertrauen'],
    ['src/platform/Telemetry/README.md', 'src/platform/Security/README.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0008',
    'ProductIntelligence',
    'Product Intelligence',
    'Product intelligence',
    'Auswertung produktbezogener Telemetrie- und Nutzungssignale zur beobachtenden Produktanalyse, ohne fachliche Entscheidungs- oder Mutationsauthority.',
    'Analysis of product-related telemetry and usage signals for observational product insight without domain decision or mutation authority.',
    'analytics',
    ['Produktintelligenz'],
    ['src/platform/Telemetry/README.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0009',
    'RateLimiting',
    'Rate Limiting',
    'Rate limiting',
    'Begrenzung der zulässigen Request- oder Aktionsfrequenz innerhalb eines definierten Zeitfensters zum Schutz von Ressourcen und Schnittstellen.',
    'Limiting the permitted request or action frequency within a defined time window to protect resources and interfaces.',
    'platform',
    ['Rate Limit', 'Ratenbegrenzung'],
    ['src/platform/Security/README.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0010',
    'ThreatModel',
    'Bedrohungsmodell',
    'Threat model',
    'Strukturierte Beschreibung relevanter Bedrohungen, Angriffsflächen, Vertrauensgrenzen und vorgesehener Gegenmaßnahmen für einen abgegrenzten Systembereich.',
    'Structured description of relevant threats, attack surfaces, trust boundaries, and intended mitigations for a bounded system area.',
    'compliance',
    ['Threat Model', 'Threat Modeling'],
    ['docs/security/VOCABULARY_WIKI_SYNC_THREAT_MODEL_2026-08-21.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0011',
    'SecurityHardening',
    'Security Hardening',
    'Security hardening',
    'Gezielte Härtung von Code, Konfiguration und Laufzeitgrenzen zur Verringerung der Angriffsfläche und zur strengeren Durchsetzung bestehender Sicherheitskontrollen.',
    'Targeted hardening of code, configuration, and runtime boundaries to reduce attack surface and more strictly enforce existing security controls.',
    'compliance',
    ['Sicherheitshärtung', 'Hardening'],
    ['src/platform/Security/README.md', 'docs/security/SECURITY_HARDENING_2026-08-29.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0012',
    'AuthenticationAssuranceLevel2',
    'Authentifizierungs-Vertrauensniveau AAL2',
    'Authentication Assurance Level 2',
    'Authentifizierungszustand mit erhöhtem Vertrauensniveau, der in der dokumentierten Supabase-MFA-Architektur einen verifizierten zweiten Faktor für privilegierte Aktionen voraussetzt.',
    'Authentication state with elevated assurance that, in the documented Supabase MFA architecture, requires a verified second factor for privileged actions.',
    'iam',
    ['AAL2', 'Assurance Level 2'],
    ['docs/adr/ADR-0064-supabase-native-mfa-aal2-hardening.md'],
    ['ADR-0064'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0013',
    'ContentSecurityPolicy',
    'Content Security Policy',
    'Content Security Policy',
    'Browser-Sicherheitsrichtlinie, die zulässige Quellen und Ausführungsgrenzen für Inhalte wie Skripte, Styles und externe Ressourcen einschränkt.',
    'Browser security policy restricting allowed sources and execution boundaries for content such as scripts, styles, and external resources.',
    'compliance',
    ['CSP'],
    ['docs/adr/ADR-0040-csp-runtime-remediation-safe-rollout.md'],
    ['ADR-0040'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0014',
    'SoftwareSupplyChainAttestation',
    'Software-Supply-Chain-Attestierung',
    'Software supply-chain attestation',
    'Kryptografisch oder signaturgestützt prüfbarer Nachweis, der Build- und Provenance-Evidence an exakte Source-, Dependency- und Artefaktidentitäten bindet.',
    'Cryptographically or signature-verifiable evidence binding build and provenance evidence to exact source, dependency, and artifact identities.',
    'release',
    ['Attestation', 'Supply-Chain-Attestierung'],
    ['docs/adr/ADR-0060-software-supply-chain-provenance-and-attestation.md'],
    ['ADR-0060'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0015',
    'SoftwareBillOfMaterials',
    'Software Bill of Materials',
    'Software Bill of Materials',
    'Maschinenlesbares Inventar der in einem Softwareartefakt enthaltenen Komponenten und Abhängigkeiten als Teil der dokumentierten Supply-Chain-Nachweiskette.',
    'Machine-readable inventory of components and dependencies contained in a software artifact as part of the documented supply-chain evidence chain.',
    'release',
    ['SBOM'],
    ['docs/adr/ADR-0060-software-supply-chain-provenance-and-attestation.md'],
    ['ADR-0060'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0016',
    'DurableOutbox',
    'Durable Outbox',
    'Durable outbox',
    'Persistente Outbox für ausstehende Arbeit oder Ereignisse, damit ein Prozessabbruch die noch nicht abgeschlossene Weiterverarbeitung nicht still verliert.',
    'Persistent outbox for pending work or events so process failure does not silently lose incomplete downstream processing.',
    'architecture',
    ['Persistente Outbox'],
    ['docs/adr/ADR-0054-durable-worker-outbox-lease.md'],
    ['ADR-0054'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0017',
    'DurableInbox',
    'Durable Inbox',
    'Durable inbox',
    'Persistente Inbox zur kontrollierten Aufnahme und Besitzzuordnung eingehender Ereignisse, bevor deren fachliche Verarbeitung abgeschlossen ist.',
    'Persistent inbox for controlled ingestion and ownership of incoming events before their domain processing is completed.',
    'architecture',
    ['Persistente Inbox'],
    ['docs/adr/ADR-0045-stripe-event-ownership-durable-inbox.md'],
    ['ADR-0045'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0018',
    'ProviderRouting',
    'Provider-Routing',
    'Provider routing',
    'Kontrollierte Auswahl und Ausweichlogik zwischen mehreren Datenprovidern unter Erhalt von Herkunft, Qualitäts- und Vertragsgrenzen.',
    'Controlled selection and fallback logic among multiple data providers while preserving provenance, quality, and contract boundaries.',
    'architecture',
    ['Multi-Provider-Routing', 'Data Provider Routing'],
    ['docs/adr/ADR-0020-multi-provider-market-data-routing.md'],
    ['ADR-0020'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0019',
    'ScreeningEligibility',
    'Screening Eligibility',
    'Screening eligibility',
    'Separater Eignungsentscheid, der bestimmt, ob ein vorhandenes Ergebnis in Screening oder Ranking verwendet werden darf, ohne den zugrunde liegenden Score selbst zu verändern.',
    'Separate eligibility decision determining whether an existing result may participate in screening or ranking without changing the underlying score itself.',
    'analytics',
    ['Screening-Eignung'],
    ['docs/adr/ADR-0025-verified-traditional-quotes-and-screening-eligibility.md'],
    ['ADR-0025'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0020',
    'PrivacyRetention',
    'Datenschutz-Retention',
    'Privacy retention',
    'Zeitlich und datenklassenspezifisch begrenzte Aufbewahrungs- und Löschlogik für operative Datenschutzdaten.',
    'Time- and data-class-bounded retention and deletion logic for operational privacy data.',
    'compliance',
    ['Retention', 'Aufbewahrungssteuerung'],
    ['docs/adr/ADR-0092-privacy-retention-and-lifecycle-hardening.md'],
    ['ADR-0092'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0021',
    'RetentionHold',
    'Retention Hold',
    'Retention hold',
    'Explizite, begrenzte Ausnahme von generischer Löschautomation, um Daten für einen autorisierten Incident-, Accountability- oder Rechtsgrund vorübergehend zu erhalten.',
    'Explicit bounded exception to generic deletion automation that temporarily preserves data for an authorized incident, accountability, or legal reason.',
    'compliance',
    ['Aufbewahrungssperre'],
    ['docs/adr/ADR-0092-privacy-retention-and-lifecycle-hardening.md'],
    ['ADR-0092'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0022',
    'DataSubjectAccessRequest',
    'Betroffenenanfrage',
    'Data subject access request',
    'Datenschutzbezogene Anfrage einer betroffenen Person, deren dokumentierter Lifecycle Identitätsprüfung, Bearbeitung und terminale Abschluss- oder Ablehnungszustände umfasst.',
    'Privacy-related request from a data subject whose documented lifecycle includes identity verification, processing, and terminal completion or rejection states.',
    'compliance',
    ['DSAR', 'Privacy Request'],
    ['docs/adr/ADR-0092-privacy-retention-and-lifecycle-hardening.md'],
    ['ADR-0092'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0023',
    'Rollback',
    'Rollback',
    'Rollback',
    'Kontrollierte Rückkehr eines Deployments oder Codes auf einen zuvor bekannten guten Zustand; ein Anwendungs-Rollback stellt Daten nicht automatisch wieder her.',
    'Controlled return of a deployment or code state to a previously known-good state; an application rollback does not automatically restore data.',
    'release',
    ['Deployment Rollback'],
    ['docs/runbooks/DEPLOYMENT_ROLLBACK_UND_BACKUP.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0024',
    'RecoveryPointObjective',
    'Recovery Point Objective',
    'Recovery Point Objective',
    'Zielgrenze für den maximal tolerierten Datenverlust zwischen dem letzten wiederherstellbaren Datenstand und einem Ausfallereignis.',
    'Target bound for the maximum tolerable data loss between the latest recoverable data point and a failure event.',
    'platform',
    ['RPO'],
    ['docs/runbooks/DEPLOYMENT_ROLLBACK_UND_BACKUP.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0025',
    'RecoveryTimeObjective',
    'Recovery Time Objective',
    'Recovery Time Objective',
    'Zielgrenze für die Zeit, innerhalb derer ein definierter Dienst oder Datenbestand nach einem Ausfall wiederhergestellt werden soll.',
    'Target bound for the time within which a defined service or data set should be restored after a failure.',
    'platform',
    ['RTO'],
    ['docs/runbooks/DEPLOYMENT_ROLLBACK_UND_BACKUP.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0026',
    'DocumentationHygiene',
    'Dokumentationshygiene',
    'Documentation hygiene',
    'Prüfung und Pflege von Dokumentationsstruktur, Lifecycle, Referenzen und Konsistenz ohne die dokumentierten fachlichen Authorities neu zu definieren.',
    'Validation and maintenance of documentation structure, lifecycle, references, and consistency without redefining the documented domain authorities.',
    'documentation',
    ['Docs Hygiene'],
    ['src/platform/Documentary/Governance/README.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0027',
    'SemanticFreshness',
    'Semantische Aktualität',
    'Semantic freshness',
    'Bewertung, ob die Bedeutung und Zustandsaussage eines Dokuments noch mit den relevanten aktuellen Quellen und Systemzuständen übereinstimmt.',
    'Assessment of whether a document’s meaning and state claims still match the relevant current sources and system state.',
    'documentation',
    ['Semantic Freshness'],
    ['src/platform/Documentary/README.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0028',
    'ArchiveRetention',
    'Archiv-Retention',
    'Archive retention',
    'Kontrollierte Aufbewahrungs- und Löschplanung für archivierte Dokumente und historische Evidence unter Erhalt notwendiger Provenance.',
    'Controlled retention and deletion planning for archived documents and historical evidence while preserving required provenance.',
    'documentation',
    ['Archivaufbewahrung'],
    ['src/platform/Documentary/README.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0029',
    'MigrationPlanning',
    'Migrationsplanung',
    'Migration planning',
    'Read-only Klassifikation und Planung von Migration, Redirect, Owner-Review oder Blockierung für Dokumente und Legacy-Oberflächen, bevor Dateien tatsächlich verändert werden.',
    'Read-only classification and planning of migration, redirect, owner review, or blocking for documents and legacy surfaces before files are actually changed.',
    'documentation',
    ['Migration Plan'],
    ['src/platform/Documentary/README.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0030',
    'TechnicalDebt',
    'Technische Schuld',
    'Technical debt',
    'Explizit erfasster technischer Verbesserungsbedarf, der Qualität, Wartbarkeit oder zukünftige Änderbarkeit beeinträchtigt, ohne unmittelbar einen Laufzeitfehler darstellen zu müssen.',
    'Explicitly tracked technical improvement need affecting quality, maintainability, or future changeability without necessarily being an immediate runtime defect.',
    'documentation',
    ['Technical Debt'],
    ['src/platform/Quality/README.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0031',
    'QualityGate',
    'Quality Gate',
    'Quality gate',
    'Prüfgrenze, die Quality-Evidence nach definierten Regeln in Zustände wie PASS, FAIL oder NOT_AVAILABLE überführt.',
    'Validation boundary that evaluates quality evidence under defined rules into states such as PASS, FAIL, or NOT_AVAILABLE.',
    'platform',
    ['Qualitäts-Gate'],
    ['src/platform/Quality/README.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0032',
    'ReleaseCandidate',
    'Release-Kandidat',
    'Release candidate',
    'Versionierter und evidenzgebundener Softwarestand oder Artefaktzustand, der für eine mögliche Release-Freigabe vorbereitet ist, aber noch nicht selbst den Release darstellt.',
    'Versioned and evidence-bound software or artifact state prepared for possible release admission but not yet the release itself.',
    'release',
    ['RC'],
    ['src/platform/Release/README.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0033',
    'DeterministicVersioning',
    'Deterministische Versionierung',
    'Deterministic versioning',
    'Reproduzierbare Ableitung und Materialisierung einer Version aus gebundener Decision-Evidence und exakter Source-Identität.',
    'Reproducible derivation and materialization of a version from bound decision evidence and exact source identity.',
    'release',
    ['Deterministic Version Materialization'],
    ['src/platform/Release/README.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0034',
    'Reconciliation',
    'Reconciliation',
    'Reconciliation',
    'Typisierter Abgleich zwischen erwartetem und beobachtetem Zustand, um Abweichungen explizit festzustellen und nachweisbar zu behandeln.',
    'Typed comparison between expected and observed state to explicitly identify and handle divergence with evidence.',
    'analytics',
    ['Abgleich'],
    ['src/platform/FinTechCore/README.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0035',
    'OrderIntent',
    'Order Intent',
    'Order intent',
    'Kanonische typisierte Repräsentation einer beabsichtigten Order vor nachgelagerter Ausführung oder Persistenz.',
    'Canonical typed representation of an intended order before downstream execution or persistence.',
    'analytics',
    ['Order-Absicht'],
    ['src/platform/FinTechCore/README.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0036',
    'PositionSizing',
    'Positionsgrößenbestimmung',
    'Position sizing',
    'Deterministische Bestimmung der Größe einer Position oder Allokation innerhalb definierter Portfolio- und Risikogrenzen.',
    'Deterministic determination of a position or allocation size within defined portfolio and risk boundaries.',
    'analytics',
    ['Position Sizing'],
    ['src/platform/FinTechCore/README.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0037',
    'PortfolioRiskEvidence',
    'Portfolio-Risk-Evidence',
    'Portfolio risk evidence',
    'Evidence-Projektion über Portfolio-Risikozustände, die Risiko nachvollziehbar macht, ohne eigenständig eine Ausführungsentscheidung zu autorisieren.',
    'Evidence projection describing portfolio risk state without independently authorizing an execution decision.',
    'analytics',
    ['Portfolio Risk Evidence'],
    ['src/platform/FinTechCore/README.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0038',
    'QuarantineWorkItem',
    'Quarantäne-Arbeitselement',
    'Quarantine work item',
    'Supervisor-Zustand, der ein Arbeitselement von weiterer Ausführung zurückhält, bis der auslösende Risiko-, Dependency- oder Evidence-Zustand geklärt ist.',
    'Supervisor state holding a work item out of further execution until the triggering risk, dependency, or evidence condition is resolved.',
    'ai-development-chat-execution',
    ['Work Item Quarantine'],
    ['src/platform/Supervisor/README.md'],
  ),
  documentationConcept(
    'VOC-DOCMIN-0039',
    'RetrySafeOperation',
    'Retry-sichere Operation',
    'Retry-safe operation',
    'Operation, deren Vertrag eine kontrollierte Wiederholung erlaubt, ohne dadurch unzulässige doppelte Seiteneffekte zu erzeugen.',
    'Operation whose contract permits controlled repetition without creating impermissible duplicate side effects.',
    'ai-development-chat-execution',
    ['Retry Safe'],
    ['src/platform/Supervisor/README.md'],
  ),
];
