import type { VocabularyConcept } from '../Domain/VocabularyConcept';

export const seedConcepts: VocabularyConcept[] = [
  {
    id: 'VOC-BILLING-0001',
    canonicalCodeTerm: 'Subscription',
    displayNameDE: 'Abonnement',
    displayNameEN: 'Subscription',
    definitionDE: 'Vertraglich definierter Nutzungszugang zu einem CAPITAL-AI Tarif.',
    definitionEN: 'Contractually defined access to a CAPITAL-AI service tier.',
    aliases: ['Abo'],
    forbiddenTerms: ['Membership'],
    category: 'billing',
    status: 'approved',
    version: '1.0.0',
    essReferences: ['ESS-0017'],
    adrReferences: ['ADR-0046'],
    traceabilityReferences: [],
  },
  {
    id: 'VOC-BILLING-0002',
    canonicalCodeTerm: 'SubscriptionTier',
    displayNameDE: 'Tarifstufe',
    displayNameEN: 'Subscription tier',
    definitionDE: 'Kanonische technische Einordnung eines Subscription-Leistungsumfangs.',
    definitionEN: 'Canonical technical classification of a subscription entitlement level.',
    aliases: ['Plan'],
    forbiddenTerms: ['PremiumPackage'],
    category: 'billing',
    status: 'approved',
    version: '1.0.0',
    essReferences: ['ESS-0017'],
    adrReferences: ['ADR-0046'],
    traceabilityReferences: [],
  },
  {
    id: 'VOC-ANALYTICS-0001',
    canonicalCodeTerm: 'Screening',
    displayNameDE: 'Screening',
    displayNameEN: 'Screening',
    definitionDE: 'Systematische Analyse eines oder mehrerer Assets anhand definierter Kriterien.',
    definitionEN: 'Systematic analysis of one or more assets against defined criteria.',
    aliases: ['Screener analysis'],
    forbiddenTerms: [],
    category: 'analytics',
    status: 'approved',
    version: '1.0.0',
    essReferences: ['ESS-0017'],
    adrReferences: ['ADR-0046'],
    traceabilityReferences: [],
  },
  {
    id: 'VOC-ANALYTICS-0002',
    canonicalCodeTerm: 'Backtest',
    displayNameDE: 'Backtest',
    displayNameEN: 'Backtest',
    definitionDE: 'Historische Simulation einer Strategie oder Regelmenge auf vergangenen Marktdaten.',
    definitionEN: 'Historical simulation of a strategy or rule set using past market data.',
    aliases: [],
    forbiddenTerms: [],
    category: 'analytics',
    status: 'approved',
    version: '1.0.0',
    essReferences: ['ESS-0017'],
    adrReferences: ['ADR-0046'],
    traceabilityReferences: [],
  },
  {
    id: 'VOC-ANALYTICS-0003',
    canonicalCodeTerm: 'MonteCarlo',
    displayNameDE: 'Monte-Carlo-Simulation',
    displayNameEN: 'Monte Carlo simulation',
    definitionDE: 'Stochastische Simulation möglicher Ergebnisverteilungen auf Basis wiederholter Zufallsziehungen.',
    definitionEN: 'Stochastic simulation of possible outcome distributions using repeated random sampling.',
    aliases: ['Monte Carlo'],
    forbiddenTerms: [],
    category: 'analytics',
    status: 'approved',
    version: '1.0.0',
    essReferences: ['ESS-0017'],
    adrReferences: ['ADR-0046'],
    traceabilityReferences: [],
  },
  {
    id: 'VOC-PLATFORM-0001',
    canonicalCodeTerm: 'VocabularyGovernance',
    displayNameDE: 'Vocabulary Governance',
    displayNameEN: 'Vocabulary Governance',
    definitionDE: 'Kanonische Governance für Terminologie, Naming, Wording und deren Lebenszyklus in CAPITAL-AI.',
    definitionEN: 'Canonical governance for terminology, naming, wording and their lifecycle in CAPITAL-AI.',
    aliases: ['Terminology Governance'],
    forbiddenTerms: [],
    category: 'platform',
    status: 'approved',
    version: '1.0.0',
    essReferences: ['ESS-0017', 'ESS-0017-CONTRACTS'],
    adrReferences: ['ADR-0046'],
    traceabilityReferences: [],
  },
];
