import type { VocabularyConcept } from '../Domain/VocabularyConcept';

const vocabularyAuthority = ['ADR-0078'];
const fintechTraceability = ['SC-MD-SPT-0001'];

export const seedConcepts: VocabularyConcept[] = [
  {
    id: 'VOC-BILLING-0001',
    canonicalCodeTerm: 'Subscription',
    displayNameDE: 'Abonnement',
    displayNameEN: 'Subscription',
    definitionDE: 'Vertraglich definierter Nutzungszugang zu einem CAPITAL-AI Tarif.',
    definitionEN: 'Contractually defined access to a CAPITAL-AI service tier.',
    aliases: ['Abo'],
    forbiddenTerms: ['Membership'],
    category: 'billing', status: 'approved', version: '1.0.0',
    essReferences: ['ESS-0017'], adrReferences: vocabularyAuthority, traceabilityReferences: [],
  },
  {
    id: 'VOC-BILLING-0002',
    canonicalCodeTerm: 'SubscriptionTier',
    displayNameDE: 'Tarifstufe',
    displayNameEN: 'Subscription tier',
    definitionDE: 'Kanonische technische Einordnung eines Subscription-Leistungsumfangs.',
    definitionEN: 'Canonical technical classification of a subscription entitlement level.',
    aliases: ['Plan'], forbiddenTerms: ['PremiumPackage'],
    category: 'billing', status: 'approved', version: '1.0.0',
    essReferences: ['ESS-0017'], adrReferences: vocabularyAuthority, traceabilityReferences: [],
  },
  {
    id: 'VOC-ANALYTICS-0001',
    canonicalCodeTerm: 'Screening',
    displayNameDE: 'Screening', displayNameEN: 'Screening',
    definitionDE: 'Systematische Analyse eines oder mehrerer Assets anhand definierter Kriterien.',
    definitionEN: 'Systematic analysis of one or more assets against defined criteria.',
    aliases: ['Screener analysis'], forbiddenTerms: [],
    category: 'analytics', status: 'approved', version: '1.0.0',
    essReferences: ['ESS-0017'], adrReferences: vocabularyAuthority, traceabilityReferences: [],
  },
  {
    id: 'VOC-ANALYTICS-0002',
    canonicalCodeTerm: 'Backtest', displayNameDE: 'Backtest', displayNameEN: 'Backtest',
    definitionDE: 'Historische Simulation einer Strategie oder Regelmenge auf vergangenen Marktdaten.',
    definitionEN: 'Historical simulation of a strategy or rule set using past market data.',
    aliases: [], forbiddenTerms: [], category: 'analytics', status: 'approved', version: '1.0.0',
    essReferences: ['ESS-0017'], adrReferences: vocabularyAuthority, traceabilityReferences: [],
  },
  {
    id: 'VOC-ANALYTICS-0003',
    canonicalCodeTerm: 'MonteCarlo', displayNameDE: 'Monte-Carlo-Simulation', displayNameEN: 'Monte Carlo simulation',
    definitionDE: 'Stochastische Simulation möglicher Ergebnisverteilungen auf Basis wiederholter Zufallsziehungen.',
    definitionEN: 'Stochastic simulation of possible outcome distributions using repeated random sampling.',
    aliases: ['Monte Carlo'], forbiddenTerms: [], category: 'analytics', status: 'approved', version: '1.0.0',
    essReferences: ['ESS-0017'], adrReferences: vocabularyAuthority, traceabilityReferences: [],
  },
  {
    id: 'VOC-PLATFORM-0001',
    canonicalCodeTerm: 'VocabularyGovernance', displayNameDE: 'Vocabulary Governance', displayNameEN: 'Vocabulary Governance',
    definitionDE: 'Kanonische Governance für Terminologie, Naming, Wording und deren Lebenszyklus in CAPITAL-AI.',
    definitionEN: 'Canonical governance for terminology, naming, wording and their lifecycle in CAPITAL-AI.',
    aliases: ['Terminology Governance'], forbiddenTerms: [], category: 'platform', status: 'approved', version: '1.0.0',
    essReferences: ['ESS-0017', 'ESS-0017-CONTRACTS'], adrReferences: vocabularyAuthority, traceabilityReferences: [],
  },

  concept('VOC-PRODUCT-0101', 'RequestIntake', 'Anfrageeingang', 'Request intake', 'Kontrollierter Eingang einer Analyse- oder Produktanfrage.', 'Controlled intake of an analysis or product request.', 'product'),
  concept('VOC-IAM-0101', 'IdentityAccess', 'Identität und Zugriff', 'Identity and access', 'Authentifizierte Identität und autorisierter Zugriff auf CAPITAL-AI Funktionen.', 'Authenticated identity and authorized access to CAPITAL-AI capabilities.', 'iam'),
  concept('VOC-BILLING-0101', 'EntitlementUsageGate', 'Berechtigungs- und Nutzungsprüfung', 'Entitlement and usage gate', 'Serverseitige Prüfung von Tarifberechtigung, Nutzung und Quota.', 'Server-side check of subscription entitlement, usage and quota.', 'billing'),
  concept('VOC-ASSET-0101', 'UniversalAssetIdentity', 'Universelle Asset-Identität', 'Universal asset identity', 'Kanonische, assetklassenübergreifende Identität eines Finanzinstruments.', 'Canonical cross-asset identity of a financial instrument.', 'asset'),
  concept('VOC-ARCHITECTURE-0101', 'RuntimeGuard', 'Runtime Guard', 'Runtime guard', 'Fail-closed Laufzeitgrenze vor der fachlichen Orchestrierung und Provider-Nutzung.', 'Fail-closed runtime boundary before domain orchestration and provider use.', 'architecture'),
  concept('VOC-ANALYTICS-0104', 'MarketEvidenceAcquisition', 'Marktdaten- und Evidence-Erfassung', 'Market-data and evidence acquisition', 'Erfassung realer Marktdaten und zugehöriger Evidence aus autorisierten Quellen.', 'Acquisition of real market data and associated evidence from authorized sources.', 'analytics'),
  concept('VOC-ANALYTICS-0105', 'DataProvenance', 'Daten-Provenance', 'Data provenance', 'Nachvollziehbare Herkunft, Qualität und Validierung verwendeter Finanzdaten.', 'Traceable origin, quality and validation of financial data in use.', 'analytics'),
  concept('VOC-PRODUCT-0102', 'VerifiedResearchDisplay', 'Verifizierte Research-Darstellung', 'Verified research display', 'Read-only Darstellung bereits validierter Research- und Evidence-Zustände.', 'Read-only display of already validated research and evidence states.', 'product'),
  concept('VOC-ANALYTICS-0106', 'FeatureClassification', 'Feature-Klassifikation', 'Feature classification', 'Kanonische Klassifikation fachlicher Features vor dem Scoring.', 'Canonical classification of domain features before scoring.', 'analytics'),
  concept('VOC-ANALYTICS-0107', 'ScoringModelRegistry', 'Scoring-Modellregister', 'Scoring model registry', 'Kanonisches Register verfügbarer und zulässiger Scoring-Modelle.', 'Canonical registry of available and permitted scoring models.', 'analytics'),
  concept('VOC-ARCHITECTURE-0102', 'ScoringDispatcher', 'Scoring Dispatcher', 'Scoring dispatcher', 'Zentrale Dispatch-Grenze für die Auswahl des zulässigen Scoring-Ausführungspfads.', 'Central dispatch boundary selecting the permitted scoring execution path.', 'architecture'),
  concept('VOC-ARCHITECTURE-0103', 'DomainExecutorAdapter', 'Domain-Executor-Adapter', 'Domain executor adapter', 'Adaptergrenze zwischen Dispatcher und domänenspezifischer Scoring-Ausführung.', 'Adapter boundary between dispatcher and domain-specific scoring execution.', 'architecture'),
  concept('VOC-ANALYTICS-0108', 'CanonicalScoreResult', 'Kanonisches Scoring-Ergebnis', 'Canonical scoring result', 'Autoritativ erzeugtes Scoring-Ergebnis mit nachvollziehbarer Execution Lineage.', 'Authoritatively produced scoring result with traceable execution lineage.', 'analytics'),
  concept('VOC-ANALYTICS-0109', 'ScoreConfidence', 'Score-Konfidenz', 'Score confidence', 'Evidenzbasierte Konfidenz eines Scoring-Ergebnisses unter Einbezug der Datenqualität.', 'Evidence-based confidence of a scoring result including data quality.', 'analytics'),
  concept('VOC-ANALYTICS-0110', 'RankingComparability', 'Ranking-Vergleichbarkeit', 'Ranking comparability', 'Prüfung, ob Ergebnisse für ein gemeinsames Ranking fachlich vergleichbar sind.', 'Check whether results are semantically comparable for a shared ranking.', 'analytics'),
  concept('VOC-ANALYTICS-0111', 'RankingEligibility', 'Ranking-Berechtigung', 'Ranking eligibility', 'Fail-closed Entscheidung, ob ein Ergebnis in ein Ranking aufgenommen werden darf.', 'Fail-closed decision whether a result may enter a ranking.', 'analytics'),
  concept('VOC-PLATFORM-0101', 'TraceabilitySupervisor', 'Traceability und Supervisor', 'Traceability and supervisor', 'Cross-cutting Evidence-, Traceability- und Supervisor-Kontext ohne fachliche Mutationsauthority.', 'Cross-cutting evidence, traceability and supervisor context without domain mutation authority.', 'platform'),
  concept('VOC-PRODUCT-0103', 'DeliverySurface', 'Ausgabeoberfläche', 'Delivery surface', 'Benutzer- oder systemseitige Ausgabeoberfläche für bereits autorisierte Ergebnisse.', 'User- or system-facing delivery surface for already authorized results.', 'product'),
];

function concept(
  id: VocabularyConcept['id'],
  canonicalCodeTerm: string,
  displayNameDE: string,
  displayNameEN: string,
  definitionDE: string,
  definitionEN: string,
  category: VocabularyConcept['category'],
): VocabularyConcept {
  return {
    id,
    canonicalCodeTerm,
    displayNameDE,
    displayNameEN,
    definitionDE,
    definitionEN,
    aliases: [],
    forbiddenTerms: [],
    category,
    status: 'approved',
    version: '1.0.0',
    essReferences: ['ESS-0017'],
    adrReferences: vocabularyAuthority,
    traceabilityReferences: fintechTraceability,
  };
}
