import type { EventContract } from '../../EventMesh/Contracts/EventContract';
import type { EventPayload } from '../../EventMesh/Contracts/EventPayload';
import type {
  OperationalTraceFreshnessState,
  OperationalTraceStateSourceRecord,
} from '../Contracts/OperationalTraceStateContract';

export const TRACEABILITY_EVENT_SOURCE_COMPONENT = 'src/platform/Traceability' as const;
export const TRACEABILITY_EVENT_FRESHNESS_MAX_AGE_MS = 60_000 as const;

export function classifyTraceabilityEventFreshness(
  sourceTimestamp: string,
  observedAt: string,
  maxAgeMs = TRACEABILITY_EVENT_FRESHNESS_MAX_AGE_MS,
): OperationalTraceFreshnessState {
  const sourceMs = Date.parse(sourceTimestamp);
  const observedMs = Date.parse(observedAt);
  if (!Number.isFinite(sourceMs) || !Number.isFinite(observedMs) || maxAgeMs < 0) return 'UNKNOWN';
  const ageMs = observedMs - sourceMs;
  if (ageMs < 0) return 'UNKNOWN';
  return ageMs <= maxAgeMs ? 'FRESH' : 'STALE';
}

/**
 * Converts one EventContract returned by the canonical EventMesh publisher into the strict
 * operational trace source shape. Identity, evidence reference, correlation and source timestamp
 * are copied verbatim from the published event. No trace identity is generated by this adapter.
 */
export function buildPublishedTraceabilityEventOperationalSource<TPayload extends EventPayload>(
  event: EventContract<TPayload>,
  observedAt = new Date().toISOString(),
): OperationalTraceStateSourceRecord {
  if (event.metadata.sourceComponent !== TRACEABILITY_EVENT_SOURCE_COMPONENT) {
    throw new Error(`Unexpected trace source component: ${event.metadata.sourceComponent}`);
  }

  const eventId = event.metadata.eventId;
  const correlationId = event.metadata.correlationId;
  const sourceTimestamp = event.metadata.timestamp;

  return {
    identity: {
      projectId: 'CAPITAL-AI-OPS',
      pvcId: 'PVC-18',
      statusId: eventId,
    },
    reportedState: 'CURRENT',
    reportedValidation: 'PASS',
    evidence: [{
      ref: eventId,
      kind: 'trace',
      label: event.metadata.name,
      identityRef: eventId,
      correlationId,
    }],
    provenance: {
      source: 'EventMesh/EventContract',
      sourceRef: eventId,
      sourceTimestamp,
      observedAt,
      freshness: classifyTraceabilityEventFreshness(sourceTimestamp, observedAt),
    },
    trace: { correlationId },
    strictEvidenceBinding: {
      mode: 'STRICT_IDENTITY_CORRELATION',
      evidenceIdentityRef: eventId,
      evidenceRef: eventId,
      correlationId,
    },
  };
}
