// ADR-0074: first catalog entry for the generalized Systemadmin work-package host. Proves the
// generic BRANCH->COMMIT->PR machinery works through the catalog lookup path instead of a
// per-work-package bespoke workflow/script (the SA4 pattern). Deliberately documentation-only,
// exactly one deterministic output file, no production effect — same bounded-pilot philosophy as
// ADR-0068's original SA4 work package, just proving the *generalization* this time instead of
// the base BRANCH/COMMIT/PR authorization chain itself.
//
// COMPLETE / VERIFIED PASS (2026-08-15, Issue #325, PR #326, see ADR-0074 Nachtrag for full
// evidence). Kept in the catalog as a reference implementation and left runnable — a re-run with
// this workPackageId now fails closed on its own via runWorkPackage.mjs's
// target-path-not-already-on-main preflight, since the target file already exists on main.

export const workPackage = Object.freeze({
  workPackageId: 'GENERALIZATION-PROOF',
  mandateId: 'REM-WORKPACKAGE-GEN-PROOF-001',
  mandateFile: '.ai/mandates/REM-WORKPACKAGE-GEN-PROOF-001.json',
  roadmapItem: 'SYSTEMADMIN-WORK-PACKAGE-CATALOG-GENERALIZATION',
  targetPath: 'docs/evidence/systemadmin-work-packages/WORK_PACKAGE_GENERALIZATION_PROOF.md',
  branchPrefix: 'agent/systemadmin-work-package-gen-proof-',
  commitMessage: 'docs(systemadmin): generalized work-package catalog runner proof',
  prTitle: 'docs(systemadmin): generalized work-package catalog runner proof',

  /**
   * Trusted, deterministic content generator. Receives only bounded execution metadata (never
   * issue-body text) and returns the exact Markdown to commit. This is the one function in the
   * whole catalog entry that decides what gets written — it is reviewed and merged to `main`
   * before it can ever run, exactly like SA4's inline template.
   */
  generate({ request, issueNumber, runId, branchAuth, branchOutcome, commitAuth }) {
    return `# Systemadmin Work-Package Catalog — Generalization Proof

Status: GENERATED BY AUDIT-BOUND SYSTEMADMIN WORK-PACKAGE HOST / HUMAN MERGE REQUIRED

This file is the deliberately bounded output of the first entry in the generalized Systemadmin
work-package catalog (ADR-0074). It proves that the catalog-driven runner
(\`scripts/systemadmin/runWorkPackage.mjs\`) can execute a pre-approved, already-reviewed work
package through the same audit-bound BRANCH -> COMMIT -> PR chain that SA4 proved for exactly one
hardcoded target (ADR-0068), without needing a brand-new workflow file or broker route per
work package. It was generated by trusted GitHub Actions host code; the triggering Issue cannot
supply this Markdown body.

## Bound execution

- Work package: \`${workPackage.workPackageId}\`
- Mandate: \`${request.mandateId}\`
- Roadmap item: \`${request.roadmapItem}\`
- Issue: \`#${issueNumber}\`
- Workflow run: \`${runId}\`
- Base SHA: \`${request.baseSha}\`
- Branch: \`${request.branchName}\`
- Path: \`${workPackage.targetPath}\`

## Pre-side-effect audit evidence

- BRANCH authorization: \`${branchAuth}\`
- BRANCH outcome: \`${branchOutcome}\`
- COMMIT authorization: \`${commitAuth}\`

## Security boundary

This work package is documentation-only. It does not request CI, deploy, mutate production,
change IAM, expose secrets, alter repository protection or merge a pull request. Final review and
merge remain Human/Owner-only. The catalog entry that produced this file is trusted, already
-merged code (\`scripts/systemadmin/workPackages/generalizationProof.mjs\`) — the triggering Issue
could only select which pre-approved work package to run, never supply file content.
`;
  },
});
