import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import type {
  SemanticFreshnessFinding,
  SemanticFreshnessReport,
} from '../../Discovery/SemanticFreshnessAnalyzer';
import type { DocumentaryDocumentType } from '../../Models/DocumentaryDocument';
import type { RegistryEntry } from '../Services/DocumentationHygieneValidator';
import {
  DOCUMENT_REGISTRY_PATH,
} from '../Services/DocumentationHygieneValidator';

export const DOCUMENTATION_VALIDATOR_VERSION = 'documentation-validator/1.4.0' as const;

export const GOV_DOC_001_RULE = Object.freeze({
  ruleId: 'GOV-DOC-001',
  name: 'Document version marking',
  area: 'DOC',
  description: 'Document without version.',
  severity: 'High',
  rationale: 'Registered documentation must declare an explicit document version in the document body.',
  essReference: 'ESS-0012-CONTRACTS Chapter 2.5',
  evidenceType: 'FileReference',
  version: '1.0.0',
} as const);

export const GOV_DOC_002_RULE = Object.freeze({
  ruleId: 'GOV-DOC-002',
  name: 'Document ESS or ADR reference',
  area: 'DOC',
  description: 'Document without ESS or ADR reference.',
  severity: 'Medium',
  rationale: 'Registered documentation must cite an explicit ESS or ADR identity in the document body.',
  essReference: 'ESS-0012-CONTRACTS Chapter 2.5',
  evidenceType: 'FileReference',
  version: '1.0.0',
} as const);

export const GOV_DOC_003_RULE = Object.freeze({
  ruleId: 'GOV-DOC-003',
  name: 'Referenced component freshness',
  area: 'DOC',
  description: 'Document is older than the last changed referenced component.',
  severity: 'Medium',
  rationale: 'Documentation must be revalidated when an explicitly referenced component changes.',
  essReference: 'ESS-0012-CONTRACTS Chapter 2.5',
  evidenceType: 'FileReference',
  version: '1.0.0',
} as const);

export const GOV_DOC_004_RULE = Object.freeze({
  ruleId: 'GOV-DOC-004',
  name: 'Document class structure',
  area: 'DOC',
  description: 'Document does not match the structure of its document class.',
  severity: 'Medium',
  rationale: 'Registered documentation must expose a heading and a class marker for its Documentary document type.',
  essReference: 'ESS-0012-CONTRACTS Chapter 2.5',
  evidenceType: 'FileReference',
  version: '1.0.0',
} as const);

export const GOV_DOC_006_RULE = Object.freeze({
  ruleId: 'GOV-DOC-006',
  name: 'Generated document generator marking',
  area: 'DOC',
  description: 'Generated document without generator marking.',
  severity: 'Medium',
  rationale: 'Generated documentation must remain attributable to a Documentary generator contract.',
  essReference: 'ESS-0012-CONTRACTS Chapter 2.5',
  evidenceType: 'FileReference',
  version: '1.0.0',
} as const);

export type DocumentationGovernanceRuleId =
  | typeof GOV_DOC_001_RULE.ruleId
  | typeof GOV_DOC_002_RULE.ruleId
  | typeof GOV_DOC_003_RULE.ruleId
  | typeof GOV_DOC_004_RULE.ruleId
  | typeof GOV_DOC_006_RULE.ruleId;

export type DocumentationGovernanceSeverity =
  | typeof GOV_DOC_001_RULE.severity
  | typeof GOV_DOC_002_RULE.severity
  | typeof GOV_DOC_003_RULE.severity;

export interface DocumentationGovernanceFileReferenceEvidence {
  type: 'FileReference';
  path: string;
  line: number;
  referencedPath: string;
  sourceCommit?: string;
  correlationId?: string;
}

export interface DocumentationGovernanceFinding {
  ruleId: DocumentationGovernanceRuleId;
  severity: DocumentationGovernanceSeverity;
  area: 'DOC';
  documentId: string;
  documentPath: string;
  message: string;
  evidence: DocumentationGovernanceFileReferenceEvidence[];
}

export const DOCUMENT_CLASS_TYPES = [
  'architecture',
  'component',
  'api',
  'runbook',
  'release-evidence',
  'handoff',
] as const satisfies readonly DocumentaryDocumentType[];

const GENERATOR_MARKERS = [
  /^\s*-\s+generiert am\s*:/i,
  /^\s*-\s+generated at\s*:/i,
  /^\s*generator\s*:/i,
  /^\s*generatedby\s*:/i,
  /<!--\s*generated by\b/i,
] as const;

const VERSION_LABEL = String.raw`(?:document(?:ation)?[\s_-]+)?(?:version|dokumentversion|dokumentenversion|fassung)`;
const VERSION_VALUE = String.raw`(?:v)?\d+(?:\.\d+){0,3}`;
const VERSION_MARKING = new RegExp(
  String.raw`(?:^|[\s,;(\[]+)` + VERSION_LABEL + String.raw`(?:\s*(?:[:|=]|is))?\s*` + VERSION_VALUE + String.raw`\b`,
  'i',
);
const AUTHORITY_REFERENCE = /\b(?:ESS|ADR)[\s_-]*\d{4}(?:-[A-Z0-9]+)?\b/i;

const DOCUMENT_CLASS_MARKERS: Record<DocumentaryDocumentType, RegExp> = {
  architecture: /architecture content|architekturinhalt|\barchitecture\b|\barchitektur\b/i,
  component: /component content|komponenteninhalt|\bcomponent\b|\bkomponente/i,
  api: /api content|api-inhalt|\bapi\b/i,
  runbook: /operational runbook|betriebsanweisung|\brunbook\b/i,
  'release-evidence': /release[ -]?evidence/i,
  handoff: /handoff content|\u00fcbergabeinhalt|\bhandoff\b|\buebergabe\b|\b\u00fcbergabe/i,
};

function isDocumentaryDocumentType(value: string): value is DocumentaryDocumentType {
  return (DOCUMENT_CLASS_TYPES as readonly string[]).includes(value);
}

function normalizeRepoPath(value: string): string {
  return value.replace(/\\/g, '/').replace(/^\.\//, '').replace(/\/+/g, '/').trim();
}

function sha256(value: string): string {
  return crypto.createHash('sha256').update(value, 'utf8').digest('hex');
}

function isComponentSourcePath(value: string): boolean {
  return /^src\/platform\/[^/]+\//i.test(normalizeRepoPath(value));
}

function resolveRegularNonSymlinkFile(repoRoot: string, relativePath: string): string | null {
  const normalized = normalizeRepoPath(relativePath);
  if (!normalized || path.isAbsolute(normalized)) return null;

  const root = path.resolve(repoRoot);
  const absolute = path.resolve(root, normalized);
  if (absolute !== root && !absolute.startsWith(`${root}${path.sep}`)) return null;
  if (!fs.existsSync(absolute)) return null;

  const stat = fs.lstatSync(absolute);
  if (!stat.isFile() || stat.isSymbolicLink()) return null;
  return absolute;
}

function explicitReferenceLine(content: string, referencedPath: string): number | null {
  const needle = normalizeRepoPath(referencedPath).toLowerCase();
  if (!needle) return null;

  const lines = content.split(/\r?\n/);
  for (let index = 0; index < lines.length; index += 1) {
    const normalizedLine = lines[index].replace(/\\/g, '/').toLowerCase();
    if (normalizedLine.includes(needle)) return index + 1;
  }
  return null;
}

function verifiedEvidenceForFinding(options: {
  repoRoot: string;
  freshness: SemanticFreshnessReport;
  finding: SemanticFreshnessFinding;
  changedPaths: ReadonlySet<string>;
}): DocumentationGovernanceFileReferenceEvidence[] {
  const { repoRoot, freshness, finding, changedPaths } = options;
  const documentPath = normalizeRepoPath(finding.path);
  if (!finding.candidate || finding.mutationClass === 'SKIP' || !finding.contentSha256) return [];
  if (changedPaths.has(documentPath)) return [];

  const absolute = resolveRegularNonSymlinkFile(repoRoot, documentPath);
  if (!absolute) return [];

  const content = fs.readFileSync(absolute, 'utf8');
  if (sha256(content) !== finding.contentSha256) return [];

  const evidence: DocumentationGovernanceFileReferenceEvidence[] = [];
  for (const sourcePathValue of finding.sourcePaths) {
    const sourcePath = normalizeRepoPath(sourcePathValue);
    if (!changedPaths.has(sourcePath) || !isComponentSourcePath(sourcePath)) continue;

    const line = explicitReferenceLine(content, sourcePath);
    if (line === null) continue;

    evidence.push({
      type: 'FileReference',
      path: documentPath,
      line,
      referencedPath: sourcePath,
      sourceCommit: freshness.sourceCommit.toLowerCase(),
      correlationId: freshness.correlationId,
    });
  }

  return evidence
    .filter((item, index, items) => items.findIndex((candidate) =>
      candidate.path === item.path
      && candidate.line === item.line
      && candidate.referencedPath === item.referencedPath
      && candidate.sourceCommit === item.sourceCommit
      && candidate.correlationId === item.correlationId) === index)
    .sort((left, right) =>
      `${left.path}:${String(left.line).padStart(10, '0')}:${left.referencedPath}`
        .localeCompare(`${right.path}:${String(right.line).padStart(10, '0')}:${right.referencedPath}`));
}

export function collectGovDoc003Findings(options: {
  repoRoot?: string;
  freshness: SemanticFreshnessReport;
}): DocumentationGovernanceFinding[] {
  const repoRoot = path.resolve(options.repoRoot ?? process.cwd());
  const { freshness } = options;

  if (!freshness.correlationId.trim()) {
    throw new Error('[DocumentationValidator] freshness correlationId is required.');
  }
  if (!/^[0-9a-f]{40}$/i.test(freshness.sourceCommit)) {
    throw new Error('[DocumentationValidator] freshness sourceCommit must be a full 40-character SHA.');
  }
  if (freshness.fullScan || freshness.sourceChanges.length === 0) return [];

  const changedPaths = new Set(
    freshness.sourceChanges
      .map((change) => normalizeRepoPath(change.path))
      .filter((sourcePath) => sourcePath.length > 0),
  );

  const findings: DocumentationGovernanceFinding[] = [];
  for (const freshnessFinding of freshness.findings) {
    const evidence = verifiedEvidenceForFinding({
      repoRoot,
      freshness,
      finding: freshnessFinding,
      changedPaths,
    });
    if (evidence.length === 0) continue;

    findings.push({
      ruleId: GOV_DOC_003_RULE.ruleId,
      severity: GOV_DOC_003_RULE.severity,
      area: GOV_DOC_003_RULE.area,
      documentId: freshnessFinding.documentId,
      documentPath: normalizeRepoPath(freshnessFinding.path),
      message: `${freshnessFinding.documentId}: document references ${evidence.length} changed component source path(s) while the document itself is unchanged in the correlated freshness evidence.`,
      evidence,
    });
  }

  return findings.sort((left, right) =>
    `${left.documentPath}:${left.documentId}:${left.ruleId}`
      .localeCompare(`${right.documentPath}:${right.documentId}:${right.ruleId}`));
}

function hasGeneratorMarking(content: string): boolean {
  return content.split(/\r?\n/).some((line) => GENERATOR_MARKERS.some((marker) => marker.test(line)));
}

function normalizeVersionText(value: string): string {
  return value
    .replace(/\r\n?/g, '\n')
    .replace(/[*_`~]+/g, ' ')
    .replace(/\[([^\]]+)\]\([^)]*\)/g, '$1')
    .replace(/<\/?[^>]+>/g, ' ')
    .replace(/[|#]+/g, ' ')
    .replace(/["\u201c\u201d\u201e']/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/^[-*+]\s+/, '');
}

function normalizeClassLine(line: string): string {
  return line.replace(/[*_`~]+/g, ' ').replace(/\s+/g, ' ').trim();
}

export function documentHasVersionMarking(content: string): boolean {
  return content.split(/\r?\n/).some((line) => VERSION_MARKING.test(normalizeVersionText(line)));
}

export function documentHasEssOrAdrReference(content: string): boolean {
  return content.split(/\r?\n/).some((line) => AUTHORITY_REFERENCE.test(normalizeVersionText(line)));
}

export function documentMatchesClassStructure(content: string, documentType: DocumentaryDocumentType): boolean {
  const lines = content.split(/\r?\n/).map(normalizeClassLine);
  const hasHeading = lines.some((line) => /^#{1,6}\s+\S/.test(line));
  const hasClass = lines.some((line) => DOCUMENT_CLASS_MARKERS[documentType].test(line));
  return hasHeading && hasClass;
}

function readRegistryEntries(repoRoot: string): RegistryEntry[] {
  const registryPath = path.join(repoRoot, DOCUMENT_REGISTRY_PATH);
  if (!fs.existsSync(registryPath)) return [];
  const parsed = JSON.parse(fs.readFileSync(registryPath, 'utf8')) as { entries?: RegistryEntry[] };
  return Array.isArray(parsed.entries) ? parsed.entries : [];
}

export function collectGovDoc006Findings(options: {
  repoRoot?: string;
  entries?: readonly RegistryEntry[];
}): DocumentationGovernanceFinding[] {
  const repoRoot = path.resolve(options.repoRoot ?? process.cwd());
  const entries = options.entries ?? readRegistryEntries(repoRoot);
  const findings: DocumentationGovernanceFinding[] = [];

  for (const entry of entries) {
    if (String(entry.lifecycle ?? '') !== 'generated') continue;

    const documentId = String(entry.documentId ?? '').trim();
    const documentPath = normalizeRepoPath(String(entry.path ?? ''));
    if (!documentId || !documentPath) continue;

    const absolute = resolveRegularNonSymlinkFile(repoRoot, documentPath);
    if (!absolute) continue;

    const content = fs.readFileSync(absolute, 'utf8');
    if (hasGeneratorMarking(content)) continue;

    findings.push({
      ruleId: GOV_DOC_006_RULE.ruleId,
      severity: GOV_DOC_006_RULE.severity,
      area: GOV_DOC_006_RULE.area,
      documentId,
      documentPath,
      message: `${documentId}: generated document has no generator marking.`,
      evidence: [{
        type: 'FileReference',
        path: documentPath,
        line: 1,
        referencedPath: documentPath,
      }],
    });
  }

  return findings.sort((left, right) =>
    `${left.documentPath}:${left.documentId}:${left.ruleId}`
      .localeCompare(`${right.documentPath}:${right.documentId}:${right.ruleId}`));
}

export function collectGovDoc001Findings(options: {
  repoRoot?: string;
  entries?: readonly RegistryEntry[];
}): DocumentationGovernanceFinding[] {
  const repoRoot = path.resolve(options.repoRoot ?? process.cwd());
  const entries = options.entries ?? readRegistryEntries(repoRoot);
  const findings: DocumentationGovernanceFinding[] = [];

  for (const entry of entries) {
    const documentId = String(entry.documentId ?? '').trim();
    const documentPath = normalizeRepoPath(String(entry.path ?? ''));
    if (!documentId || !documentPath) continue;

    const absolute = resolveRegularNonSymlinkFile(repoRoot, documentPath);
    if (!absolute) continue;

    const content = fs.readFileSync(absolute, 'utf8');
    if (documentHasVersionMarking(content)) continue;

    findings.push({
      ruleId: GOV_DOC_001_RULE.ruleId,
      severity: GOV_DOC_001_RULE.severity,
      area: GOV_DOC_001_RULE.area,
      documentId,
      documentPath,
      message: `${documentId}: registered document has no version marking.`,
      evidence: [{
        type: 'FileReference',
        path: documentPath,
        line: 1,
        referencedPath: documentPath,
      }],
    });
  }

  return findings.sort((left, right) =>
    `${left.documentPath}:${left.documentId}:${left.ruleId}`
      .localeCompare(`${right.documentPath}:${right.documentId}:${right.ruleId}`));
}

export function collectGovDoc002Findings(options: {
  repoRoot?: string;
  entries?: readonly RegistryEntry[];
}): DocumentationGovernanceFinding[] {
  const repoRoot = path.resolve(options.repoRoot ?? process.cwd());
  const entries = options.entries ?? readRegistryEntries(repoRoot);
  const findings: DocumentationGovernanceFinding[] = [];

  for (const entry of entries) {
    const documentId = String(entry.documentId ?? '').trim();
    const documentPath = normalizeRepoPath(String(entry.path ?? ''));
    if (!documentId || !documentPath) continue;

    const absolute = resolveRegularNonSymlinkFile(repoRoot, documentPath);
    if (!absolute) continue;

    const content = fs.readFileSync(absolute, 'utf8');
    if (documentHasEssOrAdrReference(content)) continue;

    findings.push({
      ruleId: GOV_DOC_002_RULE.ruleId,
      severity: GOV_DOC_002_RULE.severity,
      area: GOV_DOC_002_RULE.area,
      documentId,
      documentPath,
      message: `${documentId}: registered document has no ESS or ADR reference.`,
      evidence: [{
        type: 'FileReference',
        path: documentPath,
        line: 1,
        referencedPath: documentPath,
      }],
    });
  }

  return findings.sort((left, right) =>
    `${left.documentPath}:${left.documentId}:${left.ruleId}`
      .localeCompare(`${right.documentPath}:${right.documentId}:${right.ruleId}`));
}

export function collectGovDoc004Findings(options: {
  repoRoot?: string;
  entries?: readonly RegistryEntry[];
}): DocumentationGovernanceFinding[] {
  const repoRoot = path.resolve(options.repoRoot ?? process.cwd());
  const entries = options.entries ?? readRegistryEntries(repoRoot);
  const findings: DocumentationGovernanceFinding[] = [];

  for (const entry of entries) {
    const documentId = String(entry.documentId ?? '').trim();
    const documentPath = normalizeRepoPath(String(entry.path ?? ''));
    const documentType = String(entry.type ?? '').trim();
    if (!documentId || !documentPath || !isDocumentaryDocumentType(documentType)) continue;

    const absolute = resolveRegularNonSymlinkFile(repoRoot, documentPath);
    if (!absolute) continue;

    const content = fs.readFileSync(absolute, 'utf8');
    if (documentMatchesClassStructure(content, documentType)) continue;

    findings.push({
      ruleId: GOV_DOC_004_RULE.ruleId,
      severity: GOV_DOC_004_RULE.severity,
      area: GOV_DOC_004_RULE.area,
      documentId,
      documentPath,
      message: `${documentId}: registered ${documentType} document does not match its document-class structure.`,
      evidence: [{
        type: 'FileReference',
        path: documentPath,
        line: 1,
        referencedPath: documentPath,
      }],
    });
  }

  return findings.sort((left, right) =>
    `${left.documentPath}:${left.documentId}:${left.ruleId}`
      .localeCompare(`${right.documentPath}:${right.documentId}:${right.ruleId}`));
}
