import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { classifyPullRequestScope } from './lib.mjs';

test('documentation paths are D/P1',()=>{const result=classifyPullRequestScope(['docs/roadmaps/ROADMAP.md','.ai/skills/ESS.md']);assert.equal(result.repositoryClass,'D');assert.equal(result.checkClass,'D');assert.equal(result.executionProfile,'P1');assert.equal(result.externalMutation,'NONE');assert.ok(result.requiredChecks.includes('Live-PR-Body-Validierung'));assert.ok(result.notRequiredChecks.includes('Docker Runtime Smoke Test'));});
test('application code is C/P2',()=>{const result=classifyPullRequestScope(['src/components/ProfilePage.tsx','tests/unit/profile.test.ts']);assert.equal(result.repositoryClass,'C');assert.equal(result.checkClass,'C');assert.equal(result.executionProfile,'P2');assert.ok(result.requiredChecks.includes('Repository-Konventionen (blocking)'));});
test('workflow/runtime scope is R/P2',()=>{const result=classifyPullRequestScope(['.github/workflows/ci.yml','scripts/pr/lib.mjs']);assert.equal(result.repositoryClass,'R');assert.equal(result.checkClass,'R');assert.equal(result.executionProfile,'P2');assert.ok(result.requiredChecks.includes('Workflow-Security'));assert.ok(result.requiredChecks.includes('Docker Runtime Smoke Test'));});
test('external production mutation upgrades to M and fails closed without P3/P4',()=>{const result=classifyPullRequestScope(['docs/runbooks/change.md'],{externalMutation:'PLANNED'});assert.equal(result.repositoryClass,'D');assert.equal(result.checkClass,'M');assert.equal(result.executionProfile,'P0 HUMAN REQUIRED');assert.equal(result.mutationApprovalRequired,true);});
test('authorized P3 can describe an M handoff without granting merge',()=>{const result=classifyPullRequestScope(['render.yaml'],{externalMutation:'PLANNED',executionProfile:'P3'});assert.equal(result.checkClass,'M');assert.equal(result.executionProfile,'P3');assert.ok(result.securityNote.includes('MERGE bleibt Human/Owner-only'));});
test('feature areas are human-readable and deduplicated',()=>{const result=classifyPullRequestScope(['.github/pull_request_template.md','.github/workflows/ci.yml','docs/architecture/MONETIZATION_ROADMAP.md','docs/traceability/AI_AGENT_M0_M9_TRACEABILITY_MATRIX.md']);assert.deepEqual(result.featureAreas,['Pull-Request-Governance','CI/CD und GitHub-Automation','Monetarisierung und Kosten','Roadmap und Nachweisführung']);});
test('template v2.1 keeps the exact Owner gates, machine markers and evidence explanation',()=>{const template=fs.readFileSync('.github/pull_request_template.md','utf8');assert.ok(template.includes('CAPITAL_AI_PR_TEMPLATE_VERSION: 2.1.0'));assert.ok(template.includes('CAPITAL_AI_AUTO_CLASSIFICATION_START'));assert.ok(template.includes('CAPITAL_AI_AUTO_CLASSIFICATION_END'));assert.ok(template.includes('- [ ] Human/Owner: vollständigen PR-Diff geprüft.'));assert.ok(template.includes('- [ ] Human/Owner: alle geänderten Dateien im Tab Files changed als Viewed markiert.'));assert.ok(template.includes('Volltest-Evidence wiederverwendet'));assert.ok(template.includes('`/healthz` mit HTTP 200'));});
