#!/usr/bin/env node

import fs from 'node:fs';
import { PR_TEMPLATE_MARKER,classifyPullRequestScope,fail,githubJson,listAddedClaimFiles,listChangedFiles,readJsonFile } from './lib.mjs';
const repository=process.env.GITHUB_REPOSITORY, token=process.env.GITHUB_TOKEN||process.env.GH_TOKEN, prNumber=Number(process.env.PR_NUMBER||0), baseRef=process.env.PR_BASE_REF||'origin/main', headRef=process.env.PR_HEAD_REF||'HEAD', baselinePath=process.env.PR_BASELINE_OUTPUT||'artifacts/pr/production-baseline.json';
if (!repository) fail('GITHUB_REPOSITORY fehlt.'); if (!token) fail('GITHUB_TOKEN/GH_TOKEN fehlt.'); if (!prNumber) fail('PR_NUMBER ist für die PR-Vorlagenprüfung erforderlich.'); if (!fs.existsSync(baselinePath)) fail(`Produktions-Baseline fehlt: ${baselinePath}`);
const pr=await githubJson(`https://api.github.com/repos/${repository}/pulls/${prNumber}`,token), body=String(pr.body||''); if (!body.includes(PR_TEMPLATE_MARKER)) fail(`PR #${prNumber} verwendet nicht den Marker der kanonischen Vorlage: ${PR_TEMPLATE_MARKER}`);
const requiredSections=['## 1. Kurz erklärt','## 2. Automatisch erkannte Prüfungen','## 3. Nachvollziehbarkeit','## 4. Sicherheit und Rückweg','## 5. Human / Owner Review VOR technischer CI','## 6. Technische Nachweise','## 7. Was kann man aus diesem PR lernen?','## 8. Merge-Bereitschaft']; const missingSections=requiredSections.filter((heading)=>!body.includes(heading)); if (missingSections.length>0) fail(`PR #${prNumber} enthält nicht alle Pflichtabschnitte der kanonischen Lernvorlage: ${missingSections.join(', ')}`);
for (const marker of ['CAPITAL_AI_AUTO_CLASSIFICATION_START','CAPITAL_AI_AUTO_CLASSIFICATION_END','CAPITAL_AI_PRODUCTION_BASELINE_START','CAPITAL_AI_PRODUCTION_BASELINE_END']) if (!body.includes(marker)) fail(`PR #${prNumber} enthält den Pflichtmarker ${marker} nicht.`); const unresolved=[...body.matchAll(/\{\{([A-Z0-9_]+)\}\}/g)].map((match)=>match[1]); if (unresolved.length>0) fail(`PR #${prNumber} enthält nicht aufgelöste Vorlagenplatzhalter: ${[...new Set(unresolved)].join(', ')}`);
for (const statement of ['Human/Owner: vollständigen PR-Diff geprüft.','Human/Owner: alle geänderten Dateien im Tab Files changed als Viewed markiert.']) if (!body.includes(statement)) fail(`PR #${prNumber} enthält die kanonische Owner-Attestation nicht: ${statement}`);
const claims=listAddedClaimFiles(baseRef,headRef); if (claims.length>1) fail(`Es ist höchstens ein Work-Claim im PR-Diff zulässig; gefunden: ${claims.length}.`); const claimPath=claims[0]||null, claim=claimPath?readJsonFile(claimPath):null, baseline=readJsonFile(baselinePath), changedFiles=listChangedFiles(baseRef,headRef), classification=classifyPullRequestScope(changedFiles,{externalMutation:claim?.externalMutation||'NONE',executionProfile:claim?.executionProfile||''}); const classNames={D:'D — Dokumentation',C:'C — Anwendung/Test/Konfiguration',R:'R — Runtime/CI/Dependency/Deployment',M:'M — externe Produktionsänderung'};
const requiredEvidence=[`Repository-Scope:** ${classNames[classification.repositoryClass]}`,`Wirksame Checkklasse:** ${classNames[classification.checkClass]}`,`Execution Profile:** ${classification.executionProfile}`,`Externe Produktionsmutation:** ${classification.externalMutation}`,baseline.main?.sha,baseline.head?.sha,...(claim?[baseline.production?.commitSha,baseline.production?.version,claim.claimId,claimPath]:[])].filter(Boolean).map(String); const missingEvidence=requiredEvidence.filter((value)=>!body.includes(value)); if (missingEvidence.length>0) fail(`PR #${prNumber} ist veraltet oder falsch klassifiziert; folgende maschinelle Evidence fehlt: ${missingEvidence.join(', ')}`); for (const area of classification.featureAreas) if (!body.includes(area)) fail(`PR #${prNumber} erklärt den automatisch erkannten Feature-Bereich nicht: ${area}`); for (const check of classification.requiredChecks) if (!body.includes(check)) fail(`PR #${prNumber} listet den erforderlichen Check nicht: ${check}`); if (!body.includes('Human-/CODEOWNER-Freigabe für Merge erforderlich:** Ja')) fail('Der kanonische PR muss die Human-/CODEOWNER-Freigabe ausdrücklich beibehalten.'); console.log(`[PR-VORLAGE] PR #${prNumber} nutzt die Lernvorlage, die automatische Klasse ${classification.checkClass} und das Profil ${classification.executionProfile}; Baseline und Feature-Erklärung sind aktuell.`);
