export const ANALYSIS_REASON_CODE_CATALOG_VERSION = 'analysis-reason-codes/1.0.0' as const;

export const ANALYSIS_REASON_CODE_CATALOGS = Object.freeze({
  'RC-DQ': [
    'DQ_MISSING_EVIDENCE',
    'DQ_STALE_EVIDENCE',
    'DQ_PROVIDER_CONFLICT',
    'DQ_PROVENANCE_INCOMPLETE',
    'DQ_NOT_COMPUTABLE',
  ],
  'RC-LIQ': [
    'LIQ_SPREAD_TOO_WIDE',
    'LIQ_DEPTH_INSUFFICIENT',
    'LIQ_SLIPPAGE_EXCESSIVE',
    'LIQ_MARKET_UNAVAILABLE',
  ],
  'RC-TECH': [
    'TECH_HISTORY_INSUFFICIENT',
    'TECH_SIGNAL_CONFLICT',
    'TECH_BASELINE_WARMUP',
    'TECH_NOT_COMPUTABLE',
  ],
  'RC-MACRO': [
    'MACRO_EVENT_EVIDENCE_MISSING',
    'MACRO_SERIES_STALE',
    'MACRO_EXPECTATION_UNAVAILABLE',
  ],
  'RC-NEWS': [
    'NEWS_ENTITY_UNRESOLVED',
    'NEWS_SOURCE_UNVERIFIED',
    'NEWS_EVENT_NOT_CLASSIFIED',
    'NEWS_REACTION_NOT_VALIDATED',
  ],
  'RC-SENT': [
    'SENT_PROVIDER_EVIDENCE_MISSING',
    'SENT_SOCIAL_EVIDENCE_MISSING',
    'SENT_MANIPULATION_RISK',
    'SENT_NOT_COMPUTABLE',
  ],
  'RC-FUND': [
    'FUND_POINT_IN_TIME_EVIDENCE_MISSING',
    'FUND_PEER_SET_UNAVAILABLE',
    'FUND_REVISION_HISTORY_UNAVAILABLE',
    'FUND_DISTRESS_BLOCK',
  ],
  'RC-FLOW': [
    'FLOW_PROVIDER_EVIDENCE_MISSING',
    'FLOW_COUNTERPARTY_UNVERIFIED',
    'FLOW_ORDERBOOK_INSUFFICIENT',
  ],
  'RC-DERIV': [
    'DERIV_CHAIN_UNAVAILABLE',
    'DERIV_GREEKS_UNAVAILABLE',
    'DERIV_OPEN_INTEREST_UNAVAILABLE',
    'DERIV_FUNDING_UNAVAILABLE',
  ],
  'RC-ONCHAIN': [
    'ONCHAIN_IDENTITY_UNRESOLVED',
    'ONCHAIN_FLOW_EVIDENCE_MISSING',
    'ONCHAIN_HOLDER_EVIDENCE_MISSING',
    'ONCHAIN_SECURITY_BLOCK',
  ],
  'RC-RANK': [
    'RANK_SCORE_NOT_READY',
    'RANK_GOVERNANCE_INELIGIBLE',
    'RANK_EVIDENCE_INSUFFICIENT',
    'RANK_RISK_BLOCK',
  ],
} as const);

export type AnalysisReasonCodeCatalogId = keyof typeof ANALYSIS_REASON_CODE_CATALOGS;

export function isAnalysisReasonCodeCatalogId(value: string): value is AnalysisReasonCodeCatalogId {
  return Object.prototype.hasOwnProperty.call(ANALYSIS_REASON_CODE_CATALOGS, value);
}
